include = "**/*.bonk"

[[queries]]
name = "Monthly Account Balance"
query = """
SELECT
    STRFTIME('%Y-%m', DATE(date, 'start of month')) as month,
    (SUM(SUM(amount)) OVER (ORDER BY date)) / 100.0 as total
FROM "transaction"
INNER JOIN posting
ON "transaction".id = posting."transaction"
WHERE
  account = 'account' -- replace with desired account
GROUP BY month
ORDER BY month;
"""

[[dashboards]]
name = "Main"

  [[dashboards.components]]
  type = "text"
  template = "Hello, {{a}}!"
  variables.a = """
  SELECT 1
  """
  gridColumn = "1 / 1"
  gridRow = "auto"
  
  [[dashboards.components]]
  type = "lineChart"
  title = "Daily Total Assets"
  xAxis = "date"
  query = """
  SELECT
    date,
    (SUM(SUM(amount)) OVER (ORDER BY date)) / 100.0 as total
  FROM "transaction"
  INNER JOIN posting
  ON "transaction".id = posting."transaction"
  WHERE
    account LIKE 'assets/%'
  GROUP BY date
  ORDER BY date;
  """
  gridColumn = "1 / 4"
  gridRow = "auto"
  
  [[dashboards.components]]
  type = "lineChart"
  title = "Monthly Total Assets"
  xAxis = "month"
  query = """
  SELECT
      STRFTIME('%Y-%m', DATE(date, 'start of month')) as month,
      (SUM(SUM(amount)) OVER (ORDER BY date)) / 100.0 as total
  FROM "transaction"
  INNER JOIN posting
  ON "transaction".id = posting."transaction"
  WHERE
    account LIKE 'assets/%'
  GROUP BY month
  ORDER BY month;
  """
  gridColumn = "4 / 7"
  gridRow = "auto"
  
  [[dashboards.components]]
  type = "barChart"
  title = "Expenditures per month"
  xAxis = "month"
  query = """
  SELECT
      STRFTIME('%Y-%m', DATE(date, 'start of month')) as month,
      (SUM(amount)) / 100.0 as total
  FROM "transaction"
  INNER JOIN posting
  ON "transaction".id = posting."transaction"
  WHERE
    account LIKE 'expenses/%'
  GROUP BY month
  ORDER BY month
  """
  gridColumn = "1 / 4"
  gridRow = "auto"
  
  [[dashboards.components]]
  type = "barChart"
  title = "Income per month"
  xAxis = "month"
  query = """
  SELECT
      STRFTIME('%Y-%m', DATE(date, 'start of month')) as month,
      (SUM(amount)) / 100.0 * -1 as total
  FROM "transaction"
  INNER JOIN posting
  ON "transaction".id = posting."transaction"
  WHERE
    account LIKE 'income/%'
  GROUP BY month
  ORDER BY month
  """
  gridColumn = "4 / 7"
  gridRow = "auto"
  
  [[dashboards.components]]
  type = "barChart"
  title = "Savings per month"
  xAxis = "month"
  query = """
  SELECT
      STRFTIME('%Y-%m', DATE(date, 'start of month')) as month,
      (SUM(amount)) / 100.0 * -1 as total
  FROM "transaction"
  INNER JOIN posting
  ON "transaction".id = posting."transaction"
  WHERE
    account LIKE 'expenses/%'
    OR account LIKE 'income/%'
  GROUP BY month
  ORDER BY month
  """
  gridColumn = "1 / 7"
  gridRow = "auto"

  [[dashboards.components]]
  type = "table"
  title = "Asset Account Balances"
  query = """
  SELECT
      account,
      (SUM(amount)) / 100.0 as total
  FROM "transaction"
      INNER JOIN posting
  ON "transaction".id = posting."transaction"
  WHERE
      account LIKE 'assets/%'
  GROUP BY account
  ORDER BY total DESC
  """
  gridColumn = "1 / 3"
  gridRow = "auto"
