/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.457.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// AssetTransactionDescription : Documentation not found in the MISMO model viewer and not provided by Freddie Mac.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct AssetTransactionDescription {
    /// Asset Transaction Description String up to 3 occurances 1 required.
    #[serde(rename = "AssetTransactionDescription")]
    pub asset_transaction_description: String,
}

impl AssetTransactionDescription {
    /// Documentation not found in the MISMO model viewer and not provided by Freddie Mac.
    pub fn new(asset_transaction_description: String) -> AssetTransactionDescription {
        AssetTransactionDescription {
            asset_transaction_description,
        }
    }
}


