/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.457.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// CategoryInsightDetails : Insights object for categories.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CategoryInsightDetails {
    /// Category name.
    #[serde(rename = "name")]
    pub name: String,
    /// The number of transactions associated with this category.
    #[serde(rename = "transaction_count")]
    pub transaction_count: i32,
    /// Sum of outflow amounts.
    #[serde(rename = "total_outflows")]
    pub total_outflows: f64,
    /// Sum of inflow amounts.
    #[serde(rename = "total_inflows")]
    pub total_inflows: f64,
    /// The most common counterparties associated with this category sorted by outflow.
    #[serde(rename = "top_counterparties")]
    pub top_counterparties: Vec<crate::models::Counterparty>,
}

impl CategoryInsightDetails {
    /// Insights object for categories.
    pub fn new(name: String, transaction_count: i32, total_outflows: f64, total_inflows: f64, top_counterparties: Vec<crate::models::Counterparty>) -> CategoryInsightDetails {
        CategoryInsightDetails {
            name,
            transaction_count,
            total_outflows,
            total_inflows,
            top_counterparties,
        }
    }
}


