/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.457.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// CreditEmploymentVerification : The object containing proof of employment data for an individual.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CreditEmploymentVerification {
    /// ID of the payroll provider account.
    #[serde(rename = "account_id", deserialize_with = "Option::deserialize")]
    pub account_id: Option<String>,
    /// Current employment status.
    #[serde(rename = "status", deserialize_with = "Option::deserialize")]
    pub status: Option<String>,
    /// Start of employment in ISO 8601 format (YYYY-MM-DD).
    #[serde(rename = "start_date", deserialize_with = "Option::deserialize")]
    pub start_date: Option<String>,
    /// End of employment, if applicable. Provided in ISO 8601 format (YYY-MM-DD).
    #[serde(rename = "end_date", deserialize_with = "Option::deserialize")]
    pub end_date: Option<String>,
    #[serde(rename = "employer")]
    pub employer: crate::models::CreditEmployerVerification,
    /// Current title of employee.
    #[serde(rename = "title", deserialize_with = "Option::deserialize")]
    pub title: Option<String>,
    #[serde(rename = "platform_ids")]
    pub platform_ids: crate::models::CreditPlatformIds,
    /// The type of employment for the individual. `\"FULL_TIME\"`: A full-time employee. `\"PART_TIME\"`: A part-time employee. `\"CONTRACTOR\"`: An employee typically hired externally through a contracting group. `\"TEMPORARY\"`: A temporary employee. `\"OTHER\"`: The employee type is not one of the above defined types.
    #[serde(rename = "employee_type", deserialize_with = "Option::deserialize")]
    pub employee_type: Option<String>,
    /// The date of the employee's most recent paystub in ISO 8601 format (YYYY-MM-DD).
    #[serde(rename = "last_paystub_date", deserialize_with = "Option::deserialize")]
    pub last_paystub_date: Option<String>,
}

impl CreditEmploymentVerification {
    /// The object containing proof of employment data for an individual.
    pub fn new(account_id: Option<String>, status: Option<String>, start_date: Option<String>, end_date: Option<String>, employer: crate::models::CreditEmployerVerification, title: Option<String>, platform_ids: crate::models::CreditPlatformIds, employee_type: Option<String>, last_paystub_date: Option<String>) -> CreditEmploymentVerification {
        CreditEmploymentVerification {
            account_id,
            status,
            start_date,
            end_date,
            employer,
            title,
            platform_ids,
            employee_type,
            last_paystub_date,
        }
    }
}


