/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.457.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// IncomeOverride : Specify payroll data on the account.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct IncomeOverride {
    /// A list of paystubs associated with the account.
    #[serde(rename = "paystubs", skip_serializing_if = "Option::is_none")]
    pub paystubs: Option<Vec<crate::models::PaystubOverride>>,
}

impl IncomeOverride {
    /// Specify payroll data on the account.
    pub fn new() -> IncomeOverride {
        IncomeOverride {
            paystubs: None,
        }
    }
}


