/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.457.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// IncomeVerificationPrecheckPayrollInstitution : Information about the end user's payroll institution



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct IncomeVerificationPrecheckPayrollInstitution {
    /// The name of payroll institution
    #[serde(rename = "name", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub name: Option<Option<String>>,
}

impl IncomeVerificationPrecheckPayrollInstitution {
    /// Information about the end user's payroll institution
    pub fn new() -> IncomeVerificationPrecheckPayrollInstitution {
        IncomeVerificationPrecheckPayrollInstitution {
            name: None,
        }
    }
}


