/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.457.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// MortgagePropertyAddress : Object containing fields describing property address.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct MortgagePropertyAddress {
    /// The city name.
    #[serde(rename = "city", deserialize_with = "Option::deserialize")]
    pub city: Option<String>,
    /// The ISO 3166-1 alpha-2 country code.
    #[serde(rename = "country", deserialize_with = "Option::deserialize")]
    pub country: Option<String>,
    /// The five or nine digit postal code.
    #[serde(rename = "postal_code", deserialize_with = "Option::deserialize")]
    pub postal_code: Option<String>,
    /// The region or state (example \"NC\").
    #[serde(rename = "region", deserialize_with = "Option::deserialize")]
    pub region: Option<String>,
    /// The full street address (example \"564 Main Street, Apt 15\").
    #[serde(rename = "street", deserialize_with = "Option::deserialize")]
    pub street: Option<String>,
}

impl MortgagePropertyAddress {
    /// Object containing fields describing property address.
    pub fn new(city: Option<String>, country: Option<String>, postal_code: Option<String>, region: Option<String>, street: Option<String>) -> MortgagePropertyAddress {
        MortgagePropertyAddress {
            city,
            country,
            postal_code,
            region,
            street,
        }
    }
}


