/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.457.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// PaymentInitiationRecipientListResponse : PaymentInitiationRecipientListResponse defines the response schema for `/payment_initiation/recipient/list`



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct PaymentInitiationRecipientListResponse {
    /// An array of payment recipients created for Payment Initiation
    #[serde(rename = "recipients")]
    pub recipients: Vec<crate::models::PaymentInitiationRecipient>,
    /// A unique identifier for the request, which can be used for troubleshooting. This identifier, like all Plaid identifiers, is case sensitive.
    #[serde(rename = "request_id")]
    pub request_id: String,
}

impl PaymentInitiationRecipientListResponse {
    /// PaymentInitiationRecipientListResponse defines the response schema for `/payment_initiation/recipient/list`
    pub fn new(recipients: Vec<crate::models::PaymentInitiationRecipient>, request_id: String) -> PaymentInitiationRecipientListResponse {
        PaymentInitiationRecipientListResponse {
            recipients,
            request_id,
        }
    }
}


