/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.457.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// PayrollItemStatus : Details about the status of the payroll item.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct PayrollItemStatus {
    /// Denotes the processing status for the verification.  `UNKNOWN`: The processing status could not be determined.  `PROCESSING_COMPLETE`: The processing has completed and the user has approved for sharing. The data is available to be retrieved.  `PROCESSING`: The verification is still processing. The data is not available yet.  `FAILED`: The processing failed to complete successfully.  `APPROVAL_STATUS_PENDING`: The processing has completed but the user has not yet approved the sharing of the data.
    #[serde(rename = "processing_status", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub processing_status: Option<Option<String>>,
}

impl PayrollItemStatus {
    /// Details about the status of the payroll item.
    pub fn new() -> PayrollItemStatus {
        PayrollItemStatus {
            processing_status: None,
        }
    }
}


