/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.482.3
 * 
 * Generated by: https://openapi-generator.tech
 */

/// RiskCheckSyntheticIdentity : Field containing the data used in determining the outcome of the synthetic identity risk check.  Contains the following fields:  `score` - A score from 0 to 100 indicating the likelihood that the user is a synthetic identity.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct RiskCheckSyntheticIdentity {
    /// A score from 0 to 100 indicating the likelihood that the user is a synthetic identity.
    #[serde(rename = "score")]
    pub score: i32,
}

impl RiskCheckSyntheticIdentity {
    /// Field containing the data used in determining the outcome of the synthetic identity risk check.  Contains the following fields:  `score` - A score from 0 to 100 indicating the likelihood that the user is a synthetic identity.
    pub fn new(score: i32) -> RiskCheckSyntheticIdentity {
        RiskCheckSyntheticIdentity {
            score,
        }
    }
}


