/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.457.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// TransferCapabilitiesGetResponse : Defines the response schema for `/transfer/capabilities/get`



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct TransferCapabilitiesGetResponse {
    #[serde(rename = "institution_supported_networks")]
    pub institution_supported_networks: crate::models::InstitutionSupportedNetworks,
    /// A unique identifier for the request, which can be used for troubleshooting. This identifier, like all Plaid identifiers, is case sensitive.
    #[serde(rename = "request_id")]
    pub request_id: String,
}

impl TransferCapabilitiesGetResponse {
    /// Defines the response schema for `/transfer/capabilities/get`
    pub fn new(institution_supported_networks: crate::models::InstitutionSupportedNetworks, request_id: String) -> TransferCapabilitiesGetResponse {
        TransferCapabilitiesGetResponse {
            institution_supported_networks,
            request_id,
        }
    }
}


