/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.457.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// TransferFundingAccount : The originator's funding account, linked with Plaid Link or `/transfer/migrate_account`.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct TransferFundingAccount {
    /// The access token associated with the Item data is being requested for.
    #[serde(rename = "access_token")]
    pub access_token: String,
    /// The Plaid `account_id` for the newly created Item.
    #[serde(rename = "account_id")]
    pub account_id: String,
}

impl TransferFundingAccount {
    /// The originator's funding account, linked with Plaid Link or `/transfer/migrate_account`.
    pub fn new(access_token: String, account_id: String) -> TransferFundingAccount {
        TransferFundingAccount {
            access_token,
            account_id,
        }
    }
}


