/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.482.3
 * 
 * Generated by: https://openapi-generator.tech
 */

/// TransferLedgerBalance : Information about the balance of the ledger held with Plaid.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct TransferLedgerBalance {
    /// The amount of this balance available for use (decimal string with two digits of precision e.g. \"10.00\").
    #[serde(rename = "available")]
    pub available: String,
    /// The amount of pending funds that are in processing (decimal string with two digits of precision e.g. \"10.00\").
    #[serde(rename = "pending")]
    pub pending: String,
}

impl TransferLedgerBalance {
    /// Information about the balance of the ledger held with Plaid.
    pub fn new(available: String, pending: String) -> TransferLedgerBalance {
        TransferLedgerBalance {
            available,
            pending,
        }
    }
}


