/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.457.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// UserCreateResponse : UserCreateResponse defines the response schema for `/user/create`



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct UserCreateResponse {
    /// The user token associated with the User data is being requested for.
    #[serde(rename = "user_token")]
    pub user_token: String,
    /// The Plaid `user_id` of the User associated with this webhook, warning, or error.
    #[serde(rename = "user_id")]
    pub user_id: String,
    /// A unique identifier for the request, which can be used for troubleshooting. This identifier, like all Plaid identifiers, is case sensitive.
    #[serde(rename = "request_id")]
    pub request_id: String,
}

impl UserCreateResponse {
    /// UserCreateResponse defines the response schema for `/user/create`
    pub fn new(user_token: String, user_id: String, request_id: String) -> UserCreateResponse {
        UserCreateResponse {
            user_token,
            user_id,
            request_id,
        }
    }
}


