/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.457.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// WalletListResponse : WalletListResponse defines the response schema for `/wallet/list`



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct WalletListResponse {
    /// An array of e-wallets
    #[serde(rename = "wallets")]
    pub wallets: Vec<crate::models::Wallet>,
    /// Cursor used for fetching e-wallets created before the latest e-wallet provided in this response
    #[serde(rename = "next_cursor", skip_serializing_if = "Option::is_none")]
    pub next_cursor: Option<String>,
    /// A unique identifier for the request, which can be used for troubleshooting. This identifier, like all Plaid identifiers, is case sensitive.
    #[serde(rename = "request_id")]
    pub request_id: String,
}

impl WalletListResponse {
    /// WalletListResponse defines the response schema for `/wallet/list`
    pub fn new(wallets: Vec<crate::models::Wallet>, request_id: String) -> WalletListResponse {
        WalletListResponse {
            wallets,
            next_cursor: None,
            request_id,
        }
    }
}


