/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.482.3
 * 
 * Generated by: https://openapi-generator.tech
 */

/// WatchlistScreeningIndividualProgramListResponse : Paginated list of individual watchlist screening programs



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct WatchlistScreeningIndividualProgramListResponse {
    /// List of individual watchlist screening programs
    #[serde(rename = "watchlist_programs")]
    pub watchlist_programs: Vec<crate::models::IndividualWatchlistProgram>,
    /// An identifier that determines which page of results you receive.
    #[serde(rename = "next_cursor", deserialize_with = "Option::deserialize")]
    pub next_cursor: Option<String>,
    /// A unique identifier for the request, which can be used for troubleshooting. This identifier, like all Plaid identifiers, is case sensitive.
    #[serde(rename = "request_id")]
    pub request_id: String,
}

impl WatchlistScreeningIndividualProgramListResponse {
    /// Paginated list of individual watchlist screening programs
    pub fn new(watchlist_programs: Vec<crate::models::IndividualWatchlistProgram>, next_cursor: Option<String>, request_id: String) -> WatchlistScreeningIndividualProgramListResponse {
        WatchlistScreeningIndividualProgramListResponse {
            watchlist_programs,
            next_cursor,
            request_id,
        }
    }
}


