[package]
name = "bonk-import"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
deno_ast = { version = "1.0.0", features = ["transpiling"] }
deno_core = "0.243.0"
tokio = "1.35.1"
