[workspace]
members = [
    "bonk-ast",
    "bonk-ast-errorless",
    "bonk-check",
    "bonk-csv",
    "bonk-dashboard",
    "bonk-db",
    "bonk-http",
    "bonk-lsp",
    "bonk-plaid",
    "bonk-workspace",
    "plaid",
    "tree-sitter-bonk",
]
resolver = "2"
