[package]
name = "bonk-workspace"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glob.workspace = true
serde.workspace = true
toml.workspace = true
bonk-cfg.workspace = true
