[package]
name = "bonk-lang"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.31"
cstree = { version = "0.12.0", features = ["derive"]}
logos = "0.13.0"
