/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.586.4
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AssetReportGetResponse : AssetReportGetResponse defines the response schema for `/asset_report/get`
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AssetReportGetResponse {
    #[serde(rename = "report")]
    pub report: models::AssetReport,
    /// If the Asset Report generation was successful but identity information cannot be returned, this array will contain information about the errors causing identity information to be missing
    #[serde(rename = "warnings")]
    pub warnings: Vec<models::Warning>,
    /// A unique identifier for the request, which can be used for troubleshooting. This identifier, like all Plaid identifiers, is case sensitive.
    #[serde(rename = "request_id")]
    pub request_id: String,
}

impl AssetReportGetResponse {
    /// AssetReportGetResponse defines the response schema for `/asset_report/get`
    pub fn new(report: models::AssetReport, warnings: Vec<models::Warning>, request_id: String) -> AssetReportGetResponse {
        AssetReportGetResponse {
            report,
            warnings,
            request_id,
        }
    }
}

