/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.586.4
 * 
 * Generated by: https://openapi-generator.tech
 */

/// AssetTransactionType : Asset Transaction Type.

/// Asset Transaction Type.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum AssetTransactionType {
    #[serde(rename = "Credit")]
    Credit,
    #[serde(rename = "Debit")]
    Debit,

}

impl ToString for AssetTransactionType {
    fn to_string(&self) -> String {
        match self {
            Self::Credit => String::from("Credit"),
            Self::Debit => String::from("Debit"),
        }
    }
}

impl Default for AssetTransactionType {
    fn default() -> AssetTransactionType {
        Self::Credit
    }
}




