/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.586.4
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AssetTransactionType : Asset Transaction Type.
/// Asset Transaction Type.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum AssetTransactionType {
    #[serde(rename = "Credit")]
    Credit,
    #[serde(rename = "Debit")]
    Debit,

}

impl std::fmt::Display for AssetTransactionType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Credit => write!(f, "Credit"),
            Self::Debit => write!(f, "Debit"),
        }
    }
}

impl Default for AssetTransactionType {
    fn default() -> AssetTransactionType {
        Self::Credit
    }
}

