/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.586.4
 * 
 * Generated by: https://openapi-generator.tech
 */

/// AuthDefaultUpdateWebhook : Plaid will trigger a `DEFAULT_UPDATE` webhook for Items that undergo a change in Auth data. This is generally caused by data partners notifying Plaid of a change in their account numbering system or to their routing numbers. To avoid returned transactions, customers that receive a `DEFAULT_UPDATE` webhook with the `account_ids_with_updated_auth` object populated should immediately discontinue all usages of existing Auth data for those accounts and call `/auth/get` or `/processor/auth/get` to obtain updated account and routing numbers.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct AuthDefaultUpdateWebhook {
    /// `AUTH`
    #[serde(rename = "webhook_type")]
    pub webhook_type: String,
    /// `DEFAULT_UPDATE`
    #[serde(rename = "webhook_code")]
    pub webhook_code: String,
    /// The `item_id` of the Item associated with this webhook, warning, or error
    #[serde(rename = "item_id")]
    pub item_id: String,
    /// An array of `account_id`'s for accounts that contain new auth.
    #[serde(rename = "account_ids_with_new_auth")]
    pub account_ids_with_new_auth: Vec<String>,
    /// An object with keys of `account_id`'s that are mapped to their respective auth attributes that changed. `ACCOUNT_NUMBER` and `ROUTING_NUMBER` are the two potential values that can be flagged as updated.  Example: `{ \"XMBvvyMGQ1UoLbKByoMqH3nXMj84ALSdE5B58\": [\"ACCOUNT_NUMBER\"] }` 
    #[serde(rename = "account_ids_with_updated_auth")]
    pub account_ids_with_updated_auth: ::std::collections::HashMap<String, Vec<crate::models::AuthUpdateTypes>>,
    #[serde(rename = "error", deserialize_with = "Option::deserialize")]
    pub error: Option<crate::models::PlaidError>,
    #[serde(rename = "environment")]
    pub environment: crate::models::WebhookEnvironmentValues,
}

impl AuthDefaultUpdateWebhook {
    /// Plaid will trigger a `DEFAULT_UPDATE` webhook for Items that undergo a change in Auth data. This is generally caused by data partners notifying Plaid of a change in their account numbering system or to their routing numbers. To avoid returned transactions, customers that receive a `DEFAULT_UPDATE` webhook with the `account_ids_with_updated_auth` object populated should immediately discontinue all usages of existing Auth data for those accounts and call `/auth/get` or `/processor/auth/get` to obtain updated account and routing numbers.
    pub fn new(webhook_type: String, webhook_code: String, item_id: String, account_ids_with_new_auth: Vec<String>, account_ids_with_updated_auth: ::std::collections::HashMap<String, Vec<crate::models::AuthUpdateTypes>>, error: Option<crate::models::PlaidError>, environment: crate::models::WebhookEnvironmentValues) -> AuthDefaultUpdateWebhook {
        AuthDefaultUpdateWebhook {
            webhook_type,
            webhook_code,
            item_id,
            account_ids_with_new_auth,
            account_ids_with_updated_auth,
            error,
            environment,
        }
    }
}


