/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.586.4
 * 
 * Generated by: https://openapi-generator.tech
 */

/// BeaconAuditTrailSource : A type indicating what caused a resource to be changed or updated.   `dashboard` - The resource was created or updated by a member of your team via the Plaid dashboard.  `api` - The resource was created or updated via the Plaid API.  `system` - The resource was created or updated automatically by a part of the Plaid Beacon system. For example, if another business using Plaid Beacon created a fraud report that matched one of your users, your matching user's status would automatically be updated and the audit trail source would be `system`.  `bulk_import` - The resource was created or updated as part of a bulk import process. For example, if your company provided a CSV of user data as part of your initial onboarding, the audit trail source would be `bulk_import`.

/// A type indicating what caused a resource to be changed or updated.   `dashboard` - The resource was created or updated by a member of your team via the Plaid dashboard.  `api` - The resource was created or updated via the Plaid API.  `system` - The resource was created or updated automatically by a part of the Plaid Beacon system. For example, if another business using Plaid Beacon created a fraud report that matched one of your users, your matching user's status would automatically be updated and the audit trail source would be `system`.  `bulk_import` - The resource was created or updated as part of a bulk import process. For example, if your company provided a CSV of user data as part of your initial onboarding, the audit trail source would be `bulk_import`.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum BeaconAuditTrailSource {
    #[serde(rename = "dashboard")]
    Dashboard,
    #[serde(rename = "api")]
    Api,
    #[serde(rename = "system")]
    System,
    #[serde(rename = "bulk_import")]
    BulkImport,

}

impl ToString for BeaconAuditTrailSource {
    fn to_string(&self) -> String {
        match self {
            Self::Dashboard => String::from("dashboard"),
            Self::Api => String::from("api"),
            Self::System => String::from("system"),
            Self::BulkImport => String::from("bulk_import"),
        }
    }
}

impl Default for BeaconAuditTrailSource {
    fn default() -> BeaconAuditTrailSource {
        Self::Dashboard
    }
}




