/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.586.4
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// BeaconReportCreateRequest : Request input for creating a Beacon Report
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BeaconReportCreateRequest {
    /// ID of the associated Beacon User.
    #[serde(rename = "beacon_user_id")]
    pub beacon_user_id: String,
    #[serde(rename = "type")]
    pub r#type: models::BeaconReportCreateType,
    /// A date in the format YYYY-MM-DD (RFC 3339 Section 5.6).
    #[serde(rename = "fraud_date")]
    pub fraud_date: String,
    #[serde(rename = "fraud_amount", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub fraud_amount: Option<Option<models::FraudAmount>>,
    /// Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header or as part of a request body.
    #[serde(rename = "client_id", skip_serializing_if = "Option::is_none")]
    pub client_id: Option<String>,
    /// Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part of a request body.
    #[serde(rename = "secret", skip_serializing_if = "Option::is_none")]
    pub secret: Option<String>,
}

impl BeaconReportCreateRequest {
    /// Request input for creating a Beacon Report
    pub fn new(beacon_user_id: String, r#type: models::BeaconReportCreateType, fraud_date: String) -> BeaconReportCreateRequest {
        BeaconReportCreateRequest {
            beacon_user_id,
            r#type,
            fraud_date,
            fraud_amount: None,
            client_id: None,
            secret: None,
        }
    }
}

