/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.586.4
 * 
 * Generated by: https://openapi-generator.tech
 */

/// BeaconDuplicateGetRequest : Request input for getting a Beacon Duplicate



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct BeaconDuplicateGetRequest {
    /// ID of the associated Beacon Duplicate.
    #[serde(rename = "beacon_duplicate_id")]
    pub beacon_duplicate_id: String,
    /// Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header or as part of a request body.
    #[serde(rename = "client_id", skip_serializing_if = "Option::is_none")]
    pub client_id: Option<String>,
    /// Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part of a request body.
    #[serde(rename = "secret", skip_serializing_if = "Option::is_none")]
    pub secret: Option<String>,
}

impl BeaconDuplicateGetRequest {
    /// Request input for getting a Beacon Duplicate
    pub fn new(beacon_duplicate_id: String) -> BeaconDuplicateGetRequest {
        BeaconDuplicateGetRequest {
            beacon_duplicate_id,
            client_id: None,
            secret: None,
        }
    }
}


