/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.586.4
 * 
 * Generated by: https://openapi-generator.tech
 */

/// BeaconBankAccountInsights : Bank Account Insights encapsulate the risk insights for a single Bank Account linked to an Item that is assocaited with a Beacon User.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct BeaconBankAccountInsights {
    /// The Plaid `account_id`
    #[serde(rename = "account_id")]
    pub account_id: String,
    #[serde(rename = "type")]
    pub r#type: crate::models::AccountType,
    #[serde(rename = "subtype", deserialize_with = "Option::deserialize")]
    pub subtype: Option<crate::models::AccountSubtype>,
    #[serde(rename = "attributes")]
    pub attributes: crate::models::BeaconAccountRiskAttributes,
}

impl BeaconBankAccountInsights {
    /// Bank Account Insights encapsulate the risk insights for a single Bank Account linked to an Item that is assocaited with a Beacon User.
    pub fn new(account_id: String, r#type: crate::models::AccountType, subtype: Option<crate::models::AccountSubtype>, attributes: crate::models::BeaconAccountRiskAttributes) -> BeaconBankAccountInsights {
        BeaconBankAccountInsights {
            account_id,
            r#type,
            subtype,
            attributes,
        }
    }
}


