/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.586.4
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CraCheckReportNetworkInsightsGetResponse : CraCheckReportNetworkInsightsGetResponse defines the response schema for `/cra/check_report/network_attributes/get`.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CraCheckReportNetworkInsightsGetResponse {
    #[serde(rename = "report")]
    pub report: models::CraNetworkInsightsReport,
    /// A unique identifier for the request, which can be used for troubleshooting. This identifier, like all Plaid identifiers, is case sensitive.
    #[serde(rename = "request_id")]
    pub request_id: String,
}

impl CraCheckReportNetworkInsightsGetResponse {
    /// CraCheckReportNetworkInsightsGetResponse defines the response schema for `/cra/check_report/network_attributes/get`.
    pub fn new(report: models::CraNetworkInsightsReport, request_id: String) -> CraCheckReportNetworkInsightsGetResponse {
        CraCheckReportNetworkInsightsGetResponse {
            report,
            request_id,
        }
    }
}

