/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.586.4
 * 
 * Generated by: https://openapi-generator.tech
 */

/// CraCashflowInsightsReport : Contains data for the CRA Cashflow Insights Report.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CraCashflowInsightsReport {
    /// The unique identifier associated with the Network Attributes report object.
    #[serde(rename = "report_id")]
    pub report_id: String,
    /// The time when the Network Attributes Report was generated.
    #[serde(rename = "generated_time")]
    pub generated_time: String,
    #[serde(rename = "plaid_check_score", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub plaid_check_score: Option<Option<crate::models::PlaidCheckScore>>,
    /// A map of cashflow attributes, where the key is a string, and the value is a float, int, or boolean.
    #[serde(rename = "attributes", skip_serializing_if = "Option::is_none")]
    pub attributes: Option<serde_json::Value>,
}

impl CraCashflowInsightsReport {
    /// Contains data for the CRA Cashflow Insights Report.
    pub fn new(report_id: String, generated_time: String) -> CraCashflowInsightsReport {
        CraCashflowInsightsReport {
            report_id,
            generated_time,
            plaid_check_score: None,
            attributes: None,
        }
    }
}


