/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.586.4
 * 
 * Generated by: https://openapi-generator.tech
 */

/// CraCheckReportFailedWebhook : Fired when a Check Report has failed to generate



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CraCheckReportFailedWebhook {
    /// `CHECK_REPORT`
    #[serde(rename = "webhook_type")]
    pub webhook_type: String,
    /// `CHECK_REPORT_FAILED`
    #[serde(rename = "webhook_code")]
    pub webhook_code: String,
    /// The `user_id` corresponding to the user the webhook has fired for.
    #[serde(rename = "user_id")]
    pub user_id: String,
    #[serde(rename = "environment")]
    pub environment: crate::models::WebhookEnvironmentValues,
}

impl CraCheckReportFailedWebhook {
    /// Fired when a Check Report has failed to generate
    pub fn new(webhook_type: String, webhook_code: String, user_id: String, environment: crate::models::WebhookEnvironmentValues) -> CraCheckReportFailedWebhook {
        CraCheckReportFailedWebhook {
            webhook_type,
            webhook_code,
            user_id,
            environment,
        }
    }
}


