/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.586.4
 * 
 * Generated by: https://openapi-generator.tech
 */

/// CraLoanType : The type of loan the user applied for.

/// The type of loan the user applied for.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum CraLoanType {
    #[serde(rename = "PERSONAL")]
    Personal,
    #[serde(rename = "CREDIT_CARD")]
    CreditCard,
    #[serde(rename = "BUSINESS")]
    Business,
    #[serde(rename = "MORTGAGE")]
    Mortgage,
    #[serde(rename = "AUTO")]
    Auto,
    #[serde(rename = "PAYDAY")]
    Payday,
    #[serde(rename = "STUDENT")]
    Student,
    #[serde(rename = "HOME_EQUITY")]
    HomeEquity,
    #[serde(rename = "OTHER")]
    Other,

}

impl ToString for CraLoanType {
    fn to_string(&self) -> String {
        match self {
            Self::Personal => String::from("PERSONAL"),
            Self::CreditCard => String::from("CREDIT_CARD"),
            Self::Business => String::from("BUSINESS"),
            Self::Mortgage => String::from("MORTGAGE"),
            Self::Auto => String::from("AUTO"),
            Self::Payday => String::from("PAYDAY"),
            Self::Student => String::from("STUDENT"),
            Self::HomeEquity => String::from("HOME_EQUITY"),
            Self::Other => String::from("OTHER"),
        }
    }
}

impl Default for CraLoanType {
    fn default() -> CraLoanType {
        Self::Personal
    }
}




