/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.586.4
 * 
 * Generated by: https://openapi-generator.tech
 */

/// CraPartnerInsightsItem : The details and metadata for an end user's Item.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CraPartnerInsightsItem {
    /// The ID for the institution that the user linked.
    #[serde(rename = "institution_id", skip_serializing_if = "Option::is_none")]
    pub institution_id: Option<String>,
    /// The name of the institution the user linked.
    #[serde(rename = "institution_name", skip_serializing_if = "Option::is_none")]
    pub institution_name: Option<String>,
    /// The identifier for the item.
    #[serde(rename = "item_id", skip_serializing_if = "Option::is_none")]
    pub item_id: Option<String>,
    /// A list of accounts in the item
    #[serde(rename = "accounts", skip_serializing_if = "Option::is_none")]
    pub accounts: Option<Vec<crate::models::CraPartnerInsightsItemAccount>>,
}

impl CraPartnerInsightsItem {
    /// The details and metadata for an end user's Item.
    pub fn new() -> CraPartnerInsightsItem {
        CraPartnerInsightsItem {
            institution_id: None,
            institution_name: None,
            item_id: None,
            accounts: None,
        }
    }
}


