/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.586.4
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CraLoanRegisterApplication : Contains loan application data to register.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CraLoanRegisterApplication {
    /// A unique identifier for the loan application.  Personally identifiable information, such as an email address or phone number, should not be used in the `application_id`.
    #[serde(rename = "application_id", skip_serializing_if = "Option::is_none")]
    pub application_id: Option<String>,
    /// The date the user applied for the loan. The date should be in ISO 8601 format (YYYY-MM-DD).
    #[serde(rename = "application_date", skip_serializing_if = "Option::is_none")]
    pub application_date: Option<String>,
}

impl CraLoanRegisterApplication {
    /// Contains loan application data to register.
    pub fn new() -> CraLoanRegisterApplication {
        CraLoanRegisterApplication {
            application_id: None,
            application_date: None,
        }
    }
}

