/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.586.4
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CreditFreddieMacService : A collection of details related to a fulfillment service or product in terms of request, process and result.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreditFreddieMacService {
    #[serde(rename = "VERIFICATION_OF_ASSET")]
    pub verification_of_asset: Vec<models::CreditFreddieMacVerificationOfAsset>,
    #[serde(rename = "STATUSES")]
    pub statuses: models::Statuses,
}

impl CreditFreddieMacService {
    /// A collection of details related to a fulfillment service or product in terms of request, process and result.
    pub fn new(verification_of_asset: Vec<models::CreditFreddieMacVerificationOfAsset>, statuses: models::Statuses) -> CreditFreddieMacService {
        CreditFreddieMacService {
            verification_of_asset,
            statuses,
        }
    }
}

