/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.586.4
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CreditFreddieMacReportingInformation : Information about an report identifier and a report name.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreditFreddieMacReportingInformation {
    /// Documentation not found in the MISMO model viewer and not provided by Freddie Mac.
    #[serde(rename = "ReportDateTime", skip_serializing_if = "Option::is_none")]
    pub report_date_time: Option<String>,
    /// Documentation not found in the MISMO model viewer and not provided by Freddie Mac. The value can only be \"ReportID\"
    #[serde(rename = "ReportIdentifierType", skip_serializing_if = "Option::is_none")]
    pub report_identifier_type: Option<String>,
    /// Documentation not found in the MISMO model viewer and not provided by Freddie Mac.
    #[serde(rename = "ReportingInformationParentIdentifier", skip_serializing_if = "Option::is_none")]
    pub reporting_information_parent_identifier: Option<String>,
    /// Documentation not found in the MISMO model viewer and not provided by Freddie Mac.
    #[serde(rename = "ReportingInformationIdentifier")]
    pub reporting_information_identifier: String,
}

impl CreditFreddieMacReportingInformation {
    /// Information about an report identifier and a report name.
    pub fn new(reporting_information_identifier: String) -> CreditFreddieMacReportingInformation {
        CreditFreddieMacReportingInformation {
            report_date_time: None,
            report_identifier_type: None,
            reporting_information_parent_identifier: None,
            reporting_information_identifier,
        }
    }
}

