/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.482.3
 * 
 * Generated by: https://openapi-generator.tech
 */

/// DocumentNameMatchCode : A match summary describing the cross comparison between the subject's name, extracted from the document image, and the name they separately provided to identity verification attempt.

/// A match summary describing the cross comparison between the subject's name, extracted from the document image, and the name they separately provided to identity verification attempt.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum DocumentNameMatchCode {
    #[serde(rename = "match")]
    Match,
    #[serde(rename = "partial_match")]
    PartialMatch,
    #[serde(rename = "no_match")]
    NoMatch,

}

impl ToString for DocumentNameMatchCode {
    fn to_string(&self) -> String {
        match self {
            Self::Match => String::from("match"),
            Self::PartialMatch => String::from("partial_match"),
            Self::NoMatch => String::from("no_match"),
        }
    }
}

impl Default for DocumentNameMatchCode {
    fn default() -> DocumentNameMatchCode {
        Self::Match
    }
}




