/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.586.4
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// EmployersSearchRequest : EmployersSearchRequest defines the request schema for `/employers/search`.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EmployersSearchRequest {
    /// Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header or as part of a request body.
    #[serde(rename = "client_id", skip_serializing_if = "Option::is_none")]
    pub client_id: Option<String>,
    /// Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part of a request body.
    #[serde(rename = "secret", skip_serializing_if = "Option::is_none")]
    pub secret: Option<String>,
    /// The employer name to be searched for.
    #[serde(rename = "query")]
    pub query: String,
    /// The Plaid products the returned employers should support. Currently, this field must be set to `\"deposit_switch\"`.
    #[serde(rename = "products")]
    pub products: Vec<String>,
}

impl EmployersSearchRequest {
    /// EmployersSearchRequest defines the request schema for `/employers/search`.
    pub fn new(query: String, products: Vec<String>) -> EmployersSearchRequest {
        EmployersSearchRequest {
            client_id: None,
            secret: None,
            query,
            products,
        }
    }
}

