/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.586.4
 * 
 * Generated by: https://openapi-generator.tech
 */

/// EntityScreeningHitNamesItems : Analyzed names for the associated hit



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct EntityScreeningHitNamesItems {
    #[serde(rename = "analysis", skip_serializing_if = "Option::is_none")]
    pub analysis: Option<crate::models::MatchSummary>,
    #[serde(rename = "data", skip_serializing_if = "Option::is_none")]
    pub data: Option<crate::models::EntityScreeningHitNames>,
}

impl EntityScreeningHitNamesItems {
    /// Analyzed names for the associated hit
    pub fn new() -> EntityScreeningHitNamesItems {
        EntityScreeningHitNamesItems {
            analysis: None,
            data: None,
        }
    }
}


