/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.586.4
 * 
 * Generated by: https://openapi-generator.tech
 */

/// GetRecipientsResponse : GetRecipientsResponse defines the response schema for `/fdx/recipients`



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GetRecipientsResponse {
    #[serde(rename = "recipients")]
    pub recipients: Vec<crate::models::ExtendedRecipientMetadata>,
}

impl GetRecipientsResponse {
    /// GetRecipientsResponse defines the response schema for `/fdx/recipients`
    pub fn new(recipients: Vec<crate::models::ExtendedRecipientMetadata>) -> GetRecipientsResponse {
        GetRecipientsResponse {
            recipients,
        }
    }
}


