/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.586.4
 * 
 * Generated by: https://openapi-generator.tech
 */

/// IdentityDocumentMetadata : In closed beta. Object representing metadata pertaining to the document.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct IdentityDocumentMetadata {
    /// Boolean field indicating if the uploaded document's account number matches the account number we have on file
    #[serde(rename = "is_account_number_match", skip_serializing_if = "Option::is_none")]
    pub is_account_number_match: Option<bool>,
    #[serde(rename = "last_updated", skip_serializing_if = "Option::is_none")]
    pub last_updated: Option<String>,
    #[serde(rename = "uploaded_at", skip_serializing_if = "Option::is_none")]
    pub uploaded_at: Option<String>,
}

impl IdentityDocumentMetadata {
    /// In closed beta. Object representing metadata pertaining to the document.
    pub fn new() -> IdentityDocumentMetadata {
        IdentityDocumentMetadata {
            is_account_number_match: None,
            last_updated: None,
            uploaded_at: None,
        }
    }
}


