/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.586.4
 * 
 * Generated by: https://openapi-generator.tech
 */

/// IdentityDocumentUploadRiskSummary : Risk summary of an uploaded document.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct IdentityDocumentUploadRiskSummary {
    /// A number between 0 and 100, inclusive, where a score closer to 0 indicates a document is likely to be trustworthy and a score closer to 100 indicates a document is likely to be fraudulent.
    #[serde(rename = "risk_score", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub risk_score: Option<Option<i32>>,
}

impl IdentityDocumentUploadRiskSummary {
    /// Risk summary of an uploaded document.
    pub fn new() -> IdentityDocumentUploadRiskSummary {
        IdentityDocumentUploadRiskSummary {
            risk_score: None,
        }
    }
}


