/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.586.4
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// IdentityVerificationListResponse : Paginated list of Plaid sessions.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct IdentityVerificationListResponse {
    /// List of Plaid sessions
    #[serde(rename = "identity_verifications")]
    pub identity_verifications: Vec<models::IdentityVerification>,
    /// An identifier that determines which page of results you receive.
    #[serde(rename = "next_cursor", deserialize_with = "Option::deserialize")]
    pub next_cursor: Option<String>,
    /// A unique identifier for the request, which can be used for troubleshooting. This identifier, like all Plaid identifiers, is case sensitive.
    #[serde(rename = "request_id")]
    pub request_id: String,
}

impl IdentityVerificationListResponse {
    /// Paginated list of Plaid sessions.
    pub fn new(identity_verifications: Vec<models::IdentityVerification>, next_cursor: Option<String>, request_id: String) -> IdentityVerificationListResponse {
        IdentityVerificationListResponse {
            identity_verifications,
            next_cursor,
            request_id,
        }
    }
}

