/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.482.3
 * 
 * Generated by: https://openapi-generator.tech
 */

/// IdentityDocument : Document object with metadata of the document uploaded



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct IdentityDocument {
    #[serde(rename = "metadata", skip_serializing_if = "Option::is_none")]
    pub metadata: Option<crate::models::IdentityDocumentMetadata>,
    #[serde(rename = "document_id", skip_serializing_if = "Option::is_none")]
    pub document_id: Option<String>,
}

impl IdentityDocument {
    /// Document object with metadata of the document uploaded
    pub fn new() -> IdentityDocument {
        IdentityDocument {
            metadata: None,
            document_id: None,
        }
    }
}


