/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.482.3
 * 
 * Generated by: https://openapi-generator.tech
 */

/// IncomeVerificationSourceType : The types of source income data that users should be able to share

/// The types of source income data that users should be able to share
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum IncomeVerificationSourceType {
    #[serde(rename = "bank")]
    Bank,
    #[serde(rename = "payroll")]
    Payroll,

}

impl ToString for IncomeVerificationSourceType {
    fn to_string(&self) -> String {
        match self {
            Self::Bank => String::from("bank"),
            Self::Payroll => String::from("payroll"),
        }
    }
}

impl Default for IncomeVerificationSourceType {
    fn default() -> IncomeVerificationSourceType {
        Self::Bank
    }
}




