/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.586.4
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// IncomeVerificationSourceType : The types of source income data that users should be able to share
/// The types of source income data that users should be able to share
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum IncomeVerificationSourceType {
    #[serde(rename = "bank")]
    Bank,
    #[serde(rename = "payroll")]
    Payroll,

}

impl std::fmt::Display for IncomeVerificationSourceType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Bank => write!(f, "bank"),
            Self::Payroll => write!(f, "payroll"),
        }
    }
}

impl Default for IncomeVerificationSourceType {
    fn default() -> IncomeVerificationSourceType {
        Self::Bank
    }
}

