/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.586.4
 * 
 * Generated by: https://openapi-generator.tech
 */

/// InvestmentsTransactionsGetRequestOptions : An optional object to filter `/investments/transactions/get` results. If provided, must be non-`null`.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct InvestmentsTransactionsGetRequestOptions {
    /// An array of `account_ids` to retrieve for the Item.
    #[serde(rename = "account_ids", skip_serializing_if = "Option::is_none")]
    pub account_ids: Option<Vec<String>>,
    /// The number of transactions to fetch. 
    #[serde(rename = "count", skip_serializing_if = "Option::is_none")]
    pub count: Option<i32>,
    /// The number of transactions to skip when fetching transaction history
    #[serde(rename = "offset", skip_serializing_if = "Option::is_none")]
    pub offset: Option<i32>,
    /// If the Item was not initialized with the investments product via the `products`, `required_if_supported_products`, or `optional_products` array when calling `/link/token/create`, and `async_update` is set to true, the initial Investments extraction will happen asynchronously. Plaid will subsequently fire a `HISTORICAL_UPDATE` webhook when the extraction completes. When `false`, Plaid will wait to return a response until extraction completion and no `HISTORICAL_UPDATE` webhook will fire. Note that while the extraction is happening asynchronously, calls to `/investments/transactions/get` and `/investments/refresh` will return `PRODUCT_NOT_READY` errors until the extraction completes.
    #[serde(rename = "async_update", skip_serializing_if = "Option::is_none")]
    pub async_update: Option<bool>,
}

impl InvestmentsTransactionsGetRequestOptions {
    /// An optional object to filter `/investments/transactions/get` results. If provided, must be non-`null`.
    pub fn new() -> InvestmentsTransactionsGetRequestOptions {
        InvestmentsTransactionsGetRequestOptions {
            account_ids: None,
            count: None,
            offset: None,
            async_update: None,
        }
    }
}


