/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.586.4
 * 
 * Generated by: https://openapi-generator.tech
 */

/// IssueResolvedWebhook : Webhook notifications are sent only when a subscribed issue is marked as resolved. The payload contains details about the issue at the time of its resolution, focusing on the most essential information.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct IssueResolvedWebhook {
    /// `ISSUES`
    #[serde(rename = "webhook_type")]
    pub webhook_type: String,
    /// `ISSUE_RESOLVED`
    #[serde(rename = "webhook_code")]
    pub webhook_code: String,
    /// The unique identifier of the connectivity issue.
    #[serde(rename = "issue_id")]
    pub issue_id: String,
    /// A simple description of the error for the end user.
    #[serde(rename = "issue_description")]
    pub issue_description: String,
    /// The time when the issue was marked as resolved.
    #[serde(rename = "issue_resolved_at")]
    pub issue_resolved_at: String,
    /// The unique identifier of the financial institution involved.
    #[serde(rename = "institution_id")]
    pub institution_id: String,
    /// The name of the financial institution involved.
    #[serde(rename = "institution_name")]
    pub institution_name: String,
}

impl IssueResolvedWebhook {
    /// Webhook notifications are sent only when a subscribed issue is marked as resolved. The payload contains details about the issue at the time of its resolution, focusing on the most essential information.
    pub fn new(webhook_type: String, webhook_code: String, issue_id: String, issue_description: String, issue_resolved_at: String, institution_id: String, institution_name: String) -> IssueResolvedWebhook {
        IssueResolvedWebhook {
            webhook_type,
            webhook_code,
            issue_id,
            issue_description,
            issue_resolved_at,
            institution_id,
            institution_name,
        }
    }
}


