/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.586.4
 * 
 * Generated by: https://openapi-generator.tech
 */

/// KycCheckDetailsInternationalAddress : Result summary object specifying how the `address` field matched for fields that are only present on an international KYC check.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct KycCheckDetailsInternationalAddress {
    #[serde(rename = "building")]
    pub building: crate::models::HiddenMatchSummaryCode,
    #[serde(rename = "county")]
    pub county: crate::models::HiddenMatchSummaryCode,
    #[serde(rename = "district")]
    pub district: crate::models::HiddenMatchSummaryCode,
    #[serde(rename = "house_number")]
    pub house_number: crate::models::HiddenMatchSummaryCode,
    #[serde(rename = "subpremise")]
    pub subpremise: crate::models::HiddenMatchSummaryCode,
    #[serde(rename = "thoroughfare")]
    pub thoroughfare: crate::models::HiddenMatchSummaryCode,
}

impl KycCheckDetailsInternationalAddress {
    /// Result summary object specifying how the `address` field matched for fields that are only present on an international KYC check.
    pub fn new(building: crate::models::HiddenMatchSummaryCode, county: crate::models::HiddenMatchSummaryCode, district: crate::models::HiddenMatchSummaryCode, house_number: crate::models::HiddenMatchSummaryCode, subpremise: crate::models::HiddenMatchSummaryCode, thoroughfare: crate::models::HiddenMatchSummaryCode) -> KycCheckDetailsInternationalAddress {
        KycCheckDetailsInternationalAddress {
            building,
            county,
            district,
            house_number,
            subpremise,
            thoroughfare,
        }
    }
}


