/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.586.4
 * 
 * Generated by: https://openapi-generator.tech
 */

/// KycCheckAddressSummary : Result summary object specifying how the `address` field matched.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct KycCheckAddressSummary {
    #[serde(rename = "summary")]
    pub summary: crate::models::MatchSummaryCode,
    #[serde(rename = "po_box")]
    pub po_box: crate::models::PoBoxStatus,
    #[serde(rename = "type")]
    pub r#type: crate::models::AddressPurposeLabel,
    #[serde(rename = "street", skip_serializing_if = "Option::is_none")]
    pub street: Option<crate::models::HiddenMatchSummaryCode>,
    #[serde(rename = "city", skip_serializing_if = "Option::is_none")]
    pub city: Option<crate::models::HiddenMatchSummaryCode>,
    #[serde(rename = "region", skip_serializing_if = "Option::is_none")]
    pub region: Option<crate::models::HiddenMatchSummaryCode>,
    #[serde(rename = "postal_code", skip_serializing_if = "Option::is_none")]
    pub postal_code: Option<crate::models::HiddenMatchSummaryCode>,
    #[serde(rename = "international_details", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub international_details: Option<Option<crate::models::KycCheckDetailsInternationalAddress>>,
}

impl KycCheckAddressSummary {
    /// Result summary object specifying how the `address` field matched.
    pub fn new(summary: crate::models::MatchSummaryCode, po_box: crate::models::PoBoxStatus, r#type: crate::models::AddressPurposeLabel) -> KycCheckAddressSummary {
        KycCheckAddressSummary {
            summary,
            po_box,
            r#type,
            street: None,
            city: None,
            region: None,
            postal_code: None,
            international_details: None,
        }
    }
}


