/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.586.4
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// LiabilitiesGetResponse : LiabilitiesGetResponse defines the response schema for `/liabilities/get`
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LiabilitiesGetResponse {
    /// An array of accounts associated with the Item
    #[serde(rename = "accounts")]
    pub accounts: Vec<models::AccountBase>,
    #[serde(rename = "item")]
    pub item: models::Item,
    #[serde(rename = "liabilities")]
    pub liabilities: models::LiabilitiesObject,
    /// A unique identifier for the request, which can be used for troubleshooting. This identifier, like all Plaid identifiers, is case sensitive.
    #[serde(rename = "request_id")]
    pub request_id: String,
}

impl LiabilitiesGetResponse {
    /// LiabilitiesGetResponse defines the response schema for `/liabilities/get`
    pub fn new(accounts: Vec<models::AccountBase>, item: models::Item, liabilities: models::LiabilitiesObject, request_id: String) -> LiabilitiesGetResponse {
        LiabilitiesGetResponse {
            accounts,
            item,
            liabilities,
            request_id,
        }
    }
}

