/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.586.4
 * 
 * Generated by: https://openapi-generator.tech
 */

/// LinkTokenGetMetadataResponse : An object specifying the arguments originally provided to the `/link/token/create` call.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct LinkTokenGetMetadataResponse {
    /// The `products` specified in the `/link/token/create` call.
    #[serde(rename = "initial_products")]
    pub initial_products: Vec<crate::models::Products>,
    /// The `webhook` specified in the `/link/token/create` call.
    #[serde(rename = "webhook", deserialize_with = "Option::deserialize")]
    pub webhook: Option<String>,
    /// The `country_codes` specified in the `/link/token/create` call.
    #[serde(rename = "country_codes")]
    pub country_codes: Vec<crate::models::CountryCode>,
    /// The `language` specified in the `/link/token/create` call.
    #[serde(rename = "language", deserialize_with = "Option::deserialize")]
    pub language: Option<String>,
    #[serde(rename = "institution_data", skip_serializing_if = "Option::is_none")]
    pub institution_data: Option<Box<crate::models::LinkTokenCreateInstitutionData>>,
    #[serde(rename = "account_filters", skip_serializing_if = "Option::is_none")]
    pub account_filters: Option<crate::models::AccountFiltersResponse>,
    /// The `redirect_uri` specified in the `/link/token/create` call.
    #[serde(rename = "redirect_uri", deserialize_with = "Option::deserialize")]
    pub redirect_uri: Option<String>,
    /// The `client_name` specified in the `/link/token/create` call.
    #[serde(rename = "client_name", deserialize_with = "Option::deserialize")]
    pub client_name: Option<String>,
    /// The user token associated with the User data is being requested for.
    #[serde(rename = "user_token", skip_serializing_if = "Option::is_none")]
    pub user_token: Option<String>,
}

impl LinkTokenGetMetadataResponse {
    /// An object specifying the arguments originally provided to the `/link/token/create` call.
    pub fn new(initial_products: Vec<crate::models::Products>, webhook: Option<String>, country_codes: Vec<crate::models::CountryCode>, language: Option<String>, redirect_uri: Option<String>, client_name: Option<String>) -> LinkTokenGetMetadataResponse {
        LinkTokenGetMetadataResponse {
            initial_products,
            webhook,
            country_codes,
            language,
            institution_data: None,
            account_filters: None,
            redirect_uri,
            client_name,
            user_token: None,
        }
    }
}


