/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.586.4
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// LinkDeliveryWebhookCallbackType : The type of Link callback event
/// The type of Link callback event
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum LinkDeliveryWebhookCallbackType {
    #[serde(rename = "ON_SUCCESS")]
    Success,
    #[serde(rename = "ON_EVENT")]
    Event,
    #[serde(rename = "ON_EXIT")]
    Exit,

}

impl std::fmt::Display for LinkDeliveryWebhookCallbackType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Success => write!(f, "ON_SUCCESS"),
            Self::Event => write!(f, "ON_EVENT"),
            Self::Exit => write!(f, "ON_EXIT"),
        }
    }
}

impl Default for LinkDeliveryWebhookCallbackType {
    fn default() -> LinkDeliveryWebhookCallbackType {
        Self::Success
    }
}

