/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.586.4
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// LinkTokenCreateRequestAuth : Specifies options for initializing Link for use with the Auth product. This field can be used to enable or disable extended Auth flows for the resulting Link session. Omitting any field will result in a default that can be configured by your account manager. The default behavior described in the documentation is the default behavior that will apply if you have not requested your account manager to apply a different default.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LinkTokenCreateRequestAuth {
    /// Specifies whether Auth Type Select is enabled for the Link session, allowing the end user to choose between linking via a credentials-based flow (i.e. Instant Auth, Instant Match, Automated Micro-deposits) or a manual flow that does not require login (all other Auth flows) prior to selecting their financial institution. Default behavior is `false`.
    #[serde(rename = "auth_type_select_enabled", skip_serializing_if = "Option::is_none")]
    pub auth_type_select_enabled: Option<bool>,
    /// Specifies whether the Link session is enabled for the Automated Micro-deposits flow. Default behavior is `false`.
    #[serde(rename = "automated_microdeposits_enabled", skip_serializing_if = "Option::is_none")]
    pub automated_microdeposits_enabled: Option<bool>,
    /// Specifies whether the Link session is enabled for the Instant Match flow. Instant Match is enabled by default. Instant Match can be disabled by setting this field to `false`.
    #[serde(rename = "instant_match_enabled", skip_serializing_if = "Option::is_none")]
    pub instant_match_enabled: Option<bool>,
    /// Specifies whether the Link session is enabled for the Same Day Micro-deposits flow.  Default behavior is `false`.
    #[serde(rename = "same_day_microdeposits_enabled", skip_serializing_if = "Option::is_none")]
    pub same_day_microdeposits_enabled: Option<bool>,
    /// Specifies whether the Link session is enabled for the Instant Micro-deposits flow.  Default behavior for Plaid teams created after November 2023 is `false`; default behavior for Plaid teams created before that date is `true`.
    #[serde(rename = "instant_microdeposits_enabled", skip_serializing_if = "Option::is_none")]
    pub instant_microdeposits_enabled: Option<bool>,
    /// Specifies what type of [Reroute to Credentials](https://plaid.com/docs/auth/coverage/same-day/#reroute-to-credentials) pane should be used in the Link session for the Same Day Micro-deposits flow. Default behavior is `OPTIONAL`.
    #[serde(rename = "reroute_to_credentials", skip_serializing_if = "Option::is_none")]
    pub reroute_to_credentials: Option<RerouteToCredentials>,
    /// Specifies whether the Link session is enabled for the Database Match flow. Default behavior is `false`.
    #[serde(rename = "database_match_enabled", skip_serializing_if = "Option::is_none")]
    pub database_match_enabled: Option<bool>,
    /// Specifies whether the Link session is enabled for the Database Insights flow. Database Insights is currently in closed beta; for access, contact your Account Manager. Default behavior is `false`.
    #[serde(rename = "database_insights_enabled", skip_serializing_if = "Option::is_none")]
    pub database_insights_enabled: Option<bool>,
    /// This field has been deprecated in favor of `auth_type_select_enabled`.
    #[serde(rename = "flow_type", skip_serializing_if = "Option::is_none")]
    pub flow_type: Option<FlowType>,
    /// Specifies whether the Link session is enabled for SMS micro-deposits verification. Default behavior is `true`.
    #[serde(rename = "sms_microdeposits_verification_enabled", skip_serializing_if = "Option::is_none")]
    pub sms_microdeposits_verification_enabled: Option<bool>,
}

impl LinkTokenCreateRequestAuth {
    /// Specifies options for initializing Link for use with the Auth product. This field can be used to enable or disable extended Auth flows for the resulting Link session. Omitting any field will result in a default that can be configured by your account manager. The default behavior described in the documentation is the default behavior that will apply if you have not requested your account manager to apply a different default.
    pub fn new() -> LinkTokenCreateRequestAuth {
        LinkTokenCreateRequestAuth {
            auth_type_select_enabled: None,
            automated_microdeposits_enabled: None,
            instant_match_enabled: None,
            same_day_microdeposits_enabled: None,
            instant_microdeposits_enabled: None,
            reroute_to_credentials: None,
            database_match_enabled: None,
            database_insights_enabled: None,
            flow_type: None,
            sms_microdeposits_verification_enabled: None,
        }
    }
}
/// Specifies what type of [Reroute to Credentials](https://plaid.com/docs/auth/coverage/same-day/#reroute-to-credentials) pane should be used in the Link session for the Same Day Micro-deposits flow. Default behavior is `OPTIONAL`.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum RerouteToCredentials {
    #[serde(rename = "OFF")]
    Off,
    #[serde(rename = "OPTIONAL")]
    Optional,
    #[serde(rename = "FORCED")]
    Forced,
}

impl Default for RerouteToCredentials {
    fn default() -> RerouteToCredentials {
        Self::Off
    }
}
/// This field has been deprecated in favor of `auth_type_select_enabled`.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum FlowType {
    #[serde(rename = "FLEXIBLE_AUTH")]
    FlexibleAuth,
}

impl Default for FlowType {
    fn default() -> FlowType {
        Self::FlexibleAuth
    }
}

