/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.586.4
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// LinkTokenCreateResponse : LinkTokenCreateResponse defines the response schema for `/link/token/create`
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LinkTokenCreateResponse {
    /// A `link_token`, which can be supplied to Link in order to initialize it and receive a `public_token`, which can be exchanged for an `access_token`.
    #[serde(rename = "link_token")]
    pub link_token: String,
    /// The expiration date for the `link_token`, in [ISO 8601](https://wikipedia.org/wiki/ISO_8601) format. By default, a `link_token` created to generate a `public_token` that will be exchanged for a new `access_token` expires after 4 hours, and a `link_token` created for an existing Item (such as when updating an existing `access_token` by launching Link in update mode) expires after 30 minutes. If using [Hosted Link](https://plaid.com/docs/link/hosted-link/), the `link_token` will expire at the same time as the Hosted Link URL, and you can customize the duration using the `hosted_link.url_lifetime_seconds` option in the request. If using Link Delivery (beta), the `link_token` will expire by default after 24 hours if sent via SMS and after 7 days if sent via email.
    #[serde(rename = "expiration")]
    pub expiration: String,
    /// A unique identifier for the request, which can be used for troubleshooting. This identifier, like all Plaid identifiers, is case sensitive.
    #[serde(rename = "request_id")]
    pub request_id: String,
    /// A URL of a Plaid-hosted Link flow that will use the Link token returned by this request. Only present if the session is enabled for Hosted Link. To enable the session for Hosted Link, send a `hosted_link` object in the request.
    #[serde(rename = "hosted_link_url", skip_serializing_if = "Option::is_none")]
    pub hosted_link_url: Option<String>,
}

impl LinkTokenCreateResponse {
    /// LinkTokenCreateResponse defines the response schema for `/link/token/create`
    pub fn new(link_token: String, expiration: String, request_id: String) -> LinkTokenCreateResponse {
        LinkTokenCreateResponse {
            link_token,
            expiration,
            request_id,
            hosted_link_url: None,
        }
    }
}

