/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.586.4
 * 
 * Generated by: https://openapi-generator.tech
 */

/// LoanIdentifier : The information used to identify this loan by various parties to the transaction or other organizations.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct LoanIdentifier {
    /// The value of the identifier for the specified type.
    #[serde(rename = "LoanIdentifier", deserialize_with = "Option::deserialize")]
    pub loan_identifier: Option<String>,
    #[serde(rename = "LoanIdentifierType", deserialize_with = "Option::deserialize")]
    pub loan_identifier_type: Option<crate::models::LoanIdentifierType>,
}

impl LoanIdentifier {
    /// The information used to identify this loan by various parties to the transaction or other organizations.
    pub fn new(loan_identifier: Option<String>, loan_identifier_type: Option<crate::models::LoanIdentifierType>) -> LoanIdentifier {
        LoanIdentifier {
            loan_identifier,
            loan_identifier_type,
        }
    }
}


