/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.586.4
 * 
 * Generated by: https://openapi-generator.tech
 */

/// MonitoringInsights : An object representing the Monitoring Insights for the given Item



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct MonitoringInsights {
    #[serde(rename = "income")]
    pub income: crate::models::MonitoringIncomeInsights,
    #[serde(rename = "loans")]
    pub loans: crate::models::MonitoringLoanInsights,
}

impl MonitoringInsights {
    /// An object representing the Monitoring Insights for the given Item
    pub fn new(income: crate::models::MonitoringIncomeInsights, loans: crate::models::MonitoringLoanInsights) -> MonitoringInsights {
        MonitoringInsights {
            income,
            loans,
        }
    }
}


