/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.586.4
 * 
 * Generated by: https://openapi-generator.tech
 */

/// OwnershipType : How an asset is owned.  `association`: Ownership by a corporation, partnership, or unincorporated association, including for-profit and not-for-profit organizations. `individual`: Ownership by an individual. `joint`: Joint ownership by multiple parties. `trust`: Ownership by a revocable or irrevocable trust.

/// How an asset is owned.  `association`: Ownership by a corporation, partnership, or unincorporated association, including for-profit and not-for-profit organizations. `individual`: Ownership by an individual. `joint`: Joint ownership by multiple parties. `trust`: Ownership by a revocable or irrevocable trust.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum OwnershipType {
    #[serde(rename = "null")]
    Null,
    #[serde(rename = "individual")]
    Individual,
    #[serde(rename = "joint")]
    Joint,
    #[serde(rename = "association")]
    Association,
    #[serde(rename = "trust")]
    Trust,

}

impl ToString for OwnershipType {
    fn to_string(&self) -> String {
        match self {
            Self::Null => String::from("null"),
            Self::Individual => String::from("individual"),
            Self::Joint => String::from("joint"),
            Self::Association => String::from("association"),
            Self::Trust => String::from("trust"),
        }
    }
}

impl Default for OwnershipType {
    fn default() -> OwnershipType {
        Self::Null
    }
}




