/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.586.4
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PartnerCustomerEnableResponse : Response schema for `/partner/customer/enable`.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PartnerCustomerEnableResponse {
    /// The end customer's secret key for the Production environment.
    #[serde(rename = "production_secret", skip_serializing_if = "Option::is_none")]
    pub production_secret: Option<String>,
    /// A unique identifier for the request, which can be used for troubleshooting. This identifier, like all Plaid identifiers, is case sensitive.
    #[serde(rename = "request_id", skip_serializing_if = "Option::is_none")]
    pub request_id: Option<String>,
}

impl PartnerCustomerEnableResponse {
    /// Response schema for `/partner/customer/enable`.
    pub fn new() -> PartnerCustomerEnableResponse {
        PartnerCustomerEnableResponse {
            production_secret: None,
            request_id: None,
        }
    }
}

