/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.586.4
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PartnerEndCustomerWithSecrets : The details for the newly created end customer, including secrets for Sandbox and Limited Production.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PartnerEndCustomerWithSecrets {
    /// The `client_id` of the end customer.
    #[serde(rename = "client_id", skip_serializing_if = "Option::is_none")]
    pub client_id: Option<String>,
    /// The company name associated with the end customer.
    #[serde(rename = "company_name", skip_serializing_if = "Option::is_none")]
    pub company_name: Option<String>,
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<models::PartnerEndCustomerStatus>,
    #[serde(rename = "secrets", skip_serializing_if = "Option::is_none")]
    pub secrets: Option<models::PartnerEndCustomerSecrets>,
}

impl PartnerEndCustomerWithSecrets {
    /// The details for the newly created end customer, including secrets for Sandbox and Limited Production.
    pub fn new() -> PartnerEndCustomerWithSecrets {
        PartnerEndCustomerWithSecrets {
            client_id: None,
            company_name: None,
            status: None,
            secrets: None,
        }
    }
}

