/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.586.4
 * 
 * Generated by: https://openapi-generator.tech
 */

/// PartnerEndCustomerOAuthStatusUpdatedValues : The OAuth status of the update

/// The OAuth status of the update
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PartnerEndCustomerOAuthStatusUpdatedValues {
    #[serde(rename = "not-started")]
    NotStarted,
    #[serde(rename = "processing")]
    Processing,
    #[serde(rename = "approved")]
    Approved,
    #[serde(rename = "enabled")]
    Enabled,
    #[serde(rename = "attention-required")]
    AttentionRequired,

}

impl ToString for PartnerEndCustomerOAuthStatusUpdatedValues {
    fn to_string(&self) -> String {
        match self {
            Self::NotStarted => String::from("not-started"),
            Self::Processing => String::from("processing"),
            Self::Approved => String::from("approved"),
            Self::Enabled => String::from("enabled"),
            Self::AttentionRequired => String::from("attention-required"),
        }
    }
}

impl Default for PartnerEndCustomerOAuthStatusUpdatedValues {
    fn default() -> PartnerEndCustomerOAuthStatusUpdatedValues {
        Self::NotStarted
    }
}




