/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.586.4
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PayFrequencyValue : The frequency of the pay period.
/// The frequency of the pay period.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PayFrequencyValue {
    #[serde(rename = "monthly")]
    Monthly,
    #[serde(rename = "semimonthly")]
    Semimonthly,
    #[serde(rename = "weekly")]
    Weekly,
    #[serde(rename = "biweekly")]
    Biweekly,
    #[serde(rename = "unknown")]
    Unknown,
    #[serde(rename = "null")]
    Null,

}

impl std::fmt::Display for PayFrequencyValue {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Monthly => write!(f, "monthly"),
            Self::Semimonthly => write!(f, "semimonthly"),
            Self::Weekly => write!(f, "weekly"),
            Self::Biweekly => write!(f, "biweekly"),
            Self::Unknown => write!(f, "unknown"),
            Self::Null => write!(f, "null"),
        }
    }
}

impl Default for PayFrequencyValue {
    fn default() -> PayFrequencyValue {
        Self::Monthly
    }
}

