/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.586.4
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PaymentInitiationConsentPayerNumbers : The counterparty's bank account numbers. Exactly one of IBAN or BACS data is required.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PaymentInitiationConsentPayerNumbers {
    #[serde(rename = "bacs", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub bacs: Option<Option<Box<models::PaymentInitiationOptionalRestrictionBacs>>>,
    #[serde(rename = "iban", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub iban: Option<Option<Box<models::NumbersIbanNullable>>>,
}

impl PaymentInitiationConsentPayerNumbers {
    /// The counterparty's bank account numbers. Exactly one of IBAN or BACS data is required.
    pub fn new() -> PaymentInitiationConsentPayerNumbers {
        PaymentInitiationConsentPayerNumbers {
            bacs: None,
            iban: None,
        }
    }
}

