/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.586.4
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PaystubOverrideDeductions : An object with the deduction information found on a paystub.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PaystubOverrideDeductions {
    #[serde(rename = "breakdown", skip_serializing_if = "Option::is_none")]
    pub breakdown: Option<Vec<models::PaystubOverrideDeductionsBreakdown>>,
    #[serde(rename = "total", skip_serializing_if = "Option::is_none")]
    pub total: Option<models::PaystubOverrideDeductionsTotal>,
}

impl PaystubOverrideDeductions {
    /// An object with the deduction information found on a paystub.
    pub fn new() -> PaystubOverrideDeductions {
        PaystubOverrideDeductions {
            breakdown: None,
            total: None,
        }
    }
}

