/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.586.4
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PhoneType : An enum indicating whether a phone number is a phone line or a fax line.
/// An enum indicating whether a phone number is a phone line or a fax line.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PhoneType {
    #[serde(rename = "phone")]
    Phone,
    #[serde(rename = "fax")]
    Fax,

}

impl std::fmt::Display for PhoneType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Phone => write!(f, "phone"),
            Self::Fax => write!(f, "fax"),
        }
    }
}

impl Default for PhoneType {
    fn default() -> PhoneType {
        Self::Phone
    }
}

