/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.482.3
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ProcessorSignalReturnReportRequest : ProcessorSignalReturnReportRequest defines the request schema for `/processor/signal/return/report`



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProcessorSignalReturnReportRequest {
    /// Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header or as part of a request body.
    #[serde(rename = "client_id", skip_serializing_if = "Option::is_none")]
    pub client_id: Option<String>,
    /// Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part of a request body.
    #[serde(rename = "secret", skip_serializing_if = "Option::is_none")]
    pub secret: Option<String>,
    /// The processor token obtained from the Plaid integration partner. Processor tokens are in the format: `processor-<environment>-<identifier>`
    #[serde(rename = "processor_token")]
    pub processor_token: String,
    /// Must be the same as the `client_transaction_id` supplied when calling `/processor/signal/evaluate`
    #[serde(rename = "client_transaction_id")]
    pub client_transaction_id: String,
    /// Must be a valid ACH return code (e.g. \"R01\")  If formatted incorrectly, this will result in an [`INVALID_FIELD`](/docs/errors/invalid-request/#invalid_field) error.
    #[serde(rename = "return_code")]
    pub return_code: String,
    /// Date and time when you receive the returns from your payment processors, in ISO 8601 format (`YYYY-MM-DDTHH:mm:ssZ`).
    #[serde(rename = "returned_at", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub returned_at: Option<Option<String>>,
}

impl ProcessorSignalReturnReportRequest {
    /// ProcessorSignalReturnReportRequest defines the request schema for `/processor/signal/return/report`
    pub fn new(processor_token: String, client_transaction_id: String, return_code: String) -> ProcessorSignalReturnReportRequest {
        ProcessorSignalReturnReportRequest {
            client_id: None,
            secret: None,
            processor_token,
            client_transaction_id,
            return_code,
            returned_at: None,
        }
    }
}


