/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.586.4
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ProductStatusBreakdown : A detailed breakdown of the institution's performance for a request type. The values for `success`, `error_plaid`, and `error_institution` sum to 1. The time range used for calculating the breakdown may range from the most recent few minutes to the past six hours. In general, smaller institutions will show status that was calculated over a longer period of time. For Investment updates, which are refreshed less frequently, the period assessed may be 24 hours or more. For more details, see [Institution status details](https://plaid.com/docs/account/activity/#institution-status-details).



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ProductStatusBreakdown {
    /// The percentage of login attempts that are successful, expressed as a decimal.
    #[serde(rename = "success")]
    pub success: f64,
    /// The percentage of logins that are failing due to an internal Plaid issue, expressed as a decimal. 
    #[serde(rename = "error_plaid")]
    pub error_plaid: f64,
    /// The percentage of logins that are failing due to an issue in the institution's system, expressed as a decimal.
    #[serde(rename = "error_institution")]
    pub error_institution: f64,
    /// How frequently data for subscription products like Investments, Transactions, and Liabilities, is being refreshed, relative to the institution's normal scheduling. The `refresh_interval` may be `DELAYED` or `STOPPED` even when the success rate is high.
    #[serde(rename = "refresh_interval", skip_serializing_if = "Option::is_none")]
    pub refresh_interval: Option<RefreshInterval>,
}

impl ProductStatusBreakdown {
    /// A detailed breakdown of the institution's performance for a request type. The values for `success`, `error_plaid`, and `error_institution` sum to 1. The time range used for calculating the breakdown may range from the most recent few minutes to the past six hours. In general, smaller institutions will show status that was calculated over a longer period of time. For Investment updates, which are refreshed less frequently, the period assessed may be 24 hours or more. For more details, see [Institution status details](https://plaid.com/docs/account/activity/#institution-status-details).
    pub fn new(success: f64, error_plaid: f64, error_institution: f64) -> ProductStatusBreakdown {
        ProductStatusBreakdown {
            success,
            error_plaid,
            error_institution,
            refresh_interval: None,
        }
    }
}

/// How frequently data for subscription products like Investments, Transactions, and Liabilities, is being refreshed, relative to the institution's normal scheduling. The `refresh_interval` may be `DELAYED` or `STOPPED` even when the success rate is high.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum RefreshInterval {
    #[serde(rename = "NORMAL")]
    Normal,
    #[serde(rename = "DELAYED")]
    Delayed,
    #[serde(rename = "STOPPED")]
    Stopped,
}

impl Default for RefreshInterval {
    fn default() -> RefreshInterval {
        Self::Normal
    }
}

