/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.586.4
 * 
 * Generated by: https://openapi-generator.tech
 */

/// RiskCheckBehavior : Result summary object specifying values for `behavior` attributes of risk check, when available.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct RiskCheckBehavior {
    #[serde(rename = "user_interactions")]
    pub user_interactions: crate::models::RiskCheckBehaviorUserInteractionsLabel,
    #[serde(rename = "fraud_ring_detected")]
    pub fraud_ring_detected: crate::models::RiskCheckBehaviorFraudRingDetectedLabel,
    #[serde(rename = "bot_detected")]
    pub bot_detected: crate::models::RiskCheckBehaviorBotDetectedLabel,
}

impl RiskCheckBehavior {
    /// Result summary object specifying values for `behavior` attributes of risk check, when available.
    pub fn new(user_interactions: crate::models::RiskCheckBehaviorUserInteractionsLabel, fraud_ring_detected: crate::models::RiskCheckBehaviorFraudRingDetectedLabel, bot_detected: crate::models::RiskCheckBehaviorBotDetectedLabel) -> RiskCheckBehavior {
        RiskCheckBehavior {
            user_interactions,
            fraud_ring_detected,
            bot_detected,
        }
    }
}


