/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.586.4
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RiskSignalDocumentReference : Object containing metadata for the document
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RiskSignalDocumentReference {
    /// An identifier of the document referenced by the document metadata.
    #[serde(rename = "document_id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub document_id: Option<Option<String>>,
    /// The name of the document
    #[serde(rename = "document_name", skip_serializing_if = "Option::is_none")]
    pub document_name: Option<String>,
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<models::RiskSignalDocumentStatus>,
    #[serde(rename = "document_type", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub document_type: Option<Option<models::RiskSignalDocumentType>>,
    #[serde(rename = "file_type", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub file_type: Option<Option<models::RiskSignalFileType>>,
}

impl RiskSignalDocumentReference {
    /// Object containing metadata for the document
    pub fn new() -> RiskSignalDocumentReference {
        RiskSignalDocumentReference {
            document_id: None,
            document_name: None,
            status: None,
            document_type: None,
            file_type: None,
        }
    }
}

