/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.586.4
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RiskCheckLinkedService : An enum indicating the type of a linked service. Note that `adult_sites` refers' to explicit video content, and includes a number of related services.
/// An enum indicating the type of a linked service. Note that `adult_sites` refers' to explicit video content, and includes a number of related services.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum RiskCheckLinkedService {
    #[serde(rename = "aboutme")]
    Aboutme,
    #[serde(rename = "adobe")]
    Adobe,
    #[serde(rename = "adult_sites")]
    AdultSites,
    #[serde(rename = "airbnb")]
    Airbnb,
    #[serde(rename = "altbalaji")]
    Altbalaji,
    #[serde(rename = "amazon")]
    Amazon,
    #[serde(rename = "apple")]
    Apple,
    #[serde(rename = "archiveorg")]
    Archiveorg,
    #[serde(rename = "atlassian")]
    Atlassian,
    #[serde(rename = "bitmoji")]
    Bitmoji,
    #[serde(rename = "bodybuilding")]
    Bodybuilding,
    #[serde(rename = "booking")]
    Booking,
    #[serde(rename = "bukalapak")]
    Bukalapak,
    #[serde(rename = "codecademy")]
    Codecademy,
    #[serde(rename = "deliveroo")]
    Deliveroo,
    #[serde(rename = "diigo")]
    Diigo,
    #[serde(rename = "discord")]
    Discord,
    #[serde(rename = "disneyplus")]
    Disneyplus,
    #[serde(rename = "duolingo")]
    Duolingo,
    #[serde(rename = "ebay")]
    Ebay,
    #[serde(rename = "envato")]
    Envato,
    #[serde(rename = "eventbrite")]
    Eventbrite,
    #[serde(rename = "evernote")]
    Evernote,
    #[serde(rename = "facebook")]
    Facebook,
    #[serde(rename = "firefox")]
    Firefox,
    #[serde(rename = "flickr")]
    Flickr,
    #[serde(rename = "flipkart")]
    Flipkart,
    #[serde(rename = "foursquare")]
    Foursquare,
    #[serde(rename = "freelancer")]
    Freelancer,
    #[serde(rename = "gaana")]
    Gaana,
    #[serde(rename = "giphy")]
    Giphy,
    #[serde(rename = "github")]
    Github,
    #[serde(rename = "google")]
    Google,
    #[serde(rename = "gravatar")]
    Gravatar,
    #[serde(rename = "hubspot")]
    Hubspot,
    #[serde(rename = "imgur")]
    Imgur,
    #[serde(rename = "instagram")]
    Instagram,
    #[serde(rename = "jdid")]
    Jdid,
    #[serde(rename = "kakao")]
    Kakao,
    #[serde(rename = "kommo")]
    Kommo,
    #[serde(rename = "komoot")]
    Komoot,
    #[serde(rename = "lastfm")]
    Lastfm,
    #[serde(rename = "lazada")]
    Lazada,
    #[serde(rename = "line")]
    Line,
    #[serde(rename = "linkedin")]
    Linkedin,
    #[serde(rename = "mailru")]
    Mailru,
    #[serde(rename = "microsoft")]
    Microsoft,
    #[serde(rename = "myspace")]
    Myspace,
    #[serde(rename = "netflix")]
    Netflix,
    #[serde(rename = "nike")]
    Nike,
    #[serde(rename = "ok")]
    Ok,
    #[serde(rename = "patreon")]
    Patreon,
    #[serde(rename = "pinterest")]
    Pinterest,
    #[serde(rename = "plurk")]
    Plurk,
    #[serde(rename = "quora")]
    Quora,
    #[serde(rename = "qzone")]
    Qzone,
    #[serde(rename = "rambler")]
    Rambler,
    #[serde(rename = "rappi")]
    Rappi,
    #[serde(rename = "replit")]
    Replit,
    #[serde(rename = "samsung")]
    Samsung,
    #[serde(rename = "seoclerks")]
    Seoclerks,
    #[serde(rename = "shopclues")]
    Shopclues,
    #[serde(rename = "skype")]
    Skype,
    #[serde(rename = "snapchat")]
    Snapchat,
    #[serde(rename = "snapdeal")]
    Snapdeal,
    #[serde(rename = "soundcloud")]
    Soundcloud,
    #[serde(rename = "spotify")]
    Spotify,
    #[serde(rename = "starz")]
    Starz,
    #[serde(rename = "strava")]
    Strava,
    #[serde(rename = "taringa")]
    Taringa,
    #[serde(rename = "telegram")]
    Telegram,
    #[serde(rename = "tiki")]
    Tiki,
    #[serde(rename = "tokopedia")]
    Tokopedia,
    #[serde(rename = "treehouse")]
    Treehouse,
    #[serde(rename = "tumblr")]
    Tumblr,
    #[serde(rename = "twitter")]
    Twitter,
    #[serde(rename = "venmo")]
    Venmo,
    #[serde(rename = "viber")]
    Viber,
    #[serde(rename = "vimeo")]
    Vimeo,
    #[serde(rename = "vivino")]
    Vivino,
    #[serde(rename = "vkontakte")]
    Vkontakte,
    #[serde(rename = "wattpad")]
    Wattpad,
    #[serde(rename = "weibo")]
    Weibo,
    #[serde(rename = "whatsapp")]
    Whatsapp,
    #[serde(rename = "wordpress")]
    Wordpress,
    #[serde(rename = "xing")]
    Xing,
    #[serde(rename = "yahoo")]
    Yahoo,
    #[serde(rename = "yandex")]
    Yandex,
    #[serde(rename = "zalo")]
    Zalo,
    #[serde(rename = "zoho")]
    Zoho,

}

impl std::fmt::Display for RiskCheckLinkedService {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Aboutme => write!(f, "aboutme"),
            Self::Adobe => write!(f, "adobe"),
            Self::AdultSites => write!(f, "adult_sites"),
            Self::Airbnb => write!(f, "airbnb"),
            Self::Altbalaji => write!(f, "altbalaji"),
            Self::Amazon => write!(f, "amazon"),
            Self::Apple => write!(f, "apple"),
            Self::Archiveorg => write!(f, "archiveorg"),
            Self::Atlassian => write!(f, "atlassian"),
            Self::Bitmoji => write!(f, "bitmoji"),
            Self::Bodybuilding => write!(f, "bodybuilding"),
            Self::Booking => write!(f, "booking"),
            Self::Bukalapak => write!(f, "bukalapak"),
            Self::Codecademy => write!(f, "codecademy"),
            Self::Deliveroo => write!(f, "deliveroo"),
            Self::Diigo => write!(f, "diigo"),
            Self::Discord => write!(f, "discord"),
            Self::Disneyplus => write!(f, "disneyplus"),
            Self::Duolingo => write!(f, "duolingo"),
            Self::Ebay => write!(f, "ebay"),
            Self::Envato => write!(f, "envato"),
            Self::Eventbrite => write!(f, "eventbrite"),
            Self::Evernote => write!(f, "evernote"),
            Self::Facebook => write!(f, "facebook"),
            Self::Firefox => write!(f, "firefox"),
            Self::Flickr => write!(f, "flickr"),
            Self::Flipkart => write!(f, "flipkart"),
            Self::Foursquare => write!(f, "foursquare"),
            Self::Freelancer => write!(f, "freelancer"),
            Self::Gaana => write!(f, "gaana"),
            Self::Giphy => write!(f, "giphy"),
            Self::Github => write!(f, "github"),
            Self::Google => write!(f, "google"),
            Self::Gravatar => write!(f, "gravatar"),
            Self::Hubspot => write!(f, "hubspot"),
            Self::Imgur => write!(f, "imgur"),
            Self::Instagram => write!(f, "instagram"),
            Self::Jdid => write!(f, "jdid"),
            Self::Kakao => write!(f, "kakao"),
            Self::Kommo => write!(f, "kommo"),
            Self::Komoot => write!(f, "komoot"),
            Self::Lastfm => write!(f, "lastfm"),
            Self::Lazada => write!(f, "lazada"),
            Self::Line => write!(f, "line"),
            Self::Linkedin => write!(f, "linkedin"),
            Self::Mailru => write!(f, "mailru"),
            Self::Microsoft => write!(f, "microsoft"),
            Self::Myspace => write!(f, "myspace"),
            Self::Netflix => write!(f, "netflix"),
            Self::Nike => write!(f, "nike"),
            Self::Ok => write!(f, "ok"),
            Self::Patreon => write!(f, "patreon"),
            Self::Pinterest => write!(f, "pinterest"),
            Self::Plurk => write!(f, "plurk"),
            Self::Quora => write!(f, "quora"),
            Self::Qzone => write!(f, "qzone"),
            Self::Rambler => write!(f, "rambler"),
            Self::Rappi => write!(f, "rappi"),
            Self::Replit => write!(f, "replit"),
            Self::Samsung => write!(f, "samsung"),
            Self::Seoclerks => write!(f, "seoclerks"),
            Self::Shopclues => write!(f, "shopclues"),
            Self::Skype => write!(f, "skype"),
            Self::Snapchat => write!(f, "snapchat"),
            Self::Snapdeal => write!(f, "snapdeal"),
            Self::Soundcloud => write!(f, "soundcloud"),
            Self::Spotify => write!(f, "spotify"),
            Self::Starz => write!(f, "starz"),
            Self::Strava => write!(f, "strava"),
            Self::Taringa => write!(f, "taringa"),
            Self::Telegram => write!(f, "telegram"),
            Self::Tiki => write!(f, "tiki"),
            Self::Tokopedia => write!(f, "tokopedia"),
            Self::Treehouse => write!(f, "treehouse"),
            Self::Tumblr => write!(f, "tumblr"),
            Self::Twitter => write!(f, "twitter"),
            Self::Venmo => write!(f, "venmo"),
            Self::Viber => write!(f, "viber"),
            Self::Vimeo => write!(f, "vimeo"),
            Self::Vivino => write!(f, "vivino"),
            Self::Vkontakte => write!(f, "vkontakte"),
            Self::Wattpad => write!(f, "wattpad"),
            Self::Weibo => write!(f, "weibo"),
            Self::Whatsapp => write!(f, "whatsapp"),
            Self::Wordpress => write!(f, "wordpress"),
            Self::Xing => write!(f, "xing"),
            Self::Yahoo => write!(f, "yahoo"),
            Self::Yandex => write!(f, "yandex"),
            Self::Zalo => write!(f, "zalo"),
            Self::Zoho => write!(f, "zoho"),
        }
    }
}

impl Default for RiskCheckLinkedService {
    fn default() -> RiskCheckLinkedService {
        Self::Aboutme
    }
}

