/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.482.3
 * 
 * Generated by: https://openapi-generator.tech
 */

/// Role : ADocumentation not found in the MISMO model viewer and not provided by Freddie Mac.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Role {
    #[serde(rename = "ROLE_DETAIL")]
    pub role_detail: crate::models::RoleDetail,
}

impl Role {
    /// ADocumentation not found in the MISMO model viewer and not provided by Freddie Mac.
    pub fn new(role_detail: crate::models::RoleDetail) -> Role {
        Role {
            role_detail,
        }
    }
}


