/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.586.4
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SandboxPaymentProfileResetLoginResponse : SandboxPaymentProfileResetLoginResponse defines the response schema for `/sandbox/payment_profile/reset_login`
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SandboxPaymentProfileResetLoginResponse {
    /// `true` if the call succeeded
    #[serde(rename = "reset_login")]
    pub reset_login: bool,
    /// A unique identifier for the request, which can be used for troubleshooting. This identifier, like all Plaid identifiers, is case sensitive.
    #[serde(rename = "request_id")]
    pub request_id: String,
}

impl SandboxPaymentProfileResetLoginResponse {
    /// SandboxPaymentProfileResetLoginResponse defines the response schema for `/sandbox/payment_profile/reset_login`
    pub fn new(reset_login: bool, request_id: String) -> SandboxPaymentProfileResetLoginResponse {
        SandboxPaymentProfileResetLoginResponse {
            reset_login,
            request_id,
        }
    }
}

