/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.586.4
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SandboxTransferTestClockGetResponse : Defines the response schema for `/sandbox/transfer/test_clock/get`
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SandboxTransferTestClockGetResponse {
    #[serde(rename = "test_clock")]
    pub test_clock: models::TransferTestClock,
    /// A unique identifier for the request, which can be used for troubleshooting. This identifier, like all Plaid identifiers, is case sensitive.
    #[serde(rename = "request_id")]
    pub request_id: String,
}

impl SandboxTransferTestClockGetResponse {
    /// Defines the response schema for `/sandbox/transfer/test_clock/get`
    pub fn new(test_clock: models::TransferTestClock, request_id: String) -> SandboxTransferTestClockGetResponse {
        SandboxTransferTestClockGetResponse {
            test_clock,
            request_id,
        }
    }
}

