/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.586.4
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SandboxIncomeWebhookFireRequestWebhookCode : The webhook codes that can be fired by this test endpoint.
/// The webhook codes that can be fired by this test endpoint.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum SandboxIncomeWebhookFireRequestWebhookCode {
    #[serde(rename = "INCOME_VERIFICATION")]
    Verification,
    #[serde(rename = "INCOME_VERIFICATION_RISK_SIGNALS")]
    VerificationRiskSignals,

}

impl std::fmt::Display for SandboxIncomeWebhookFireRequestWebhookCode {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Verification => write!(f, "INCOME_VERIFICATION"),
            Self::VerificationRiskSignals => write!(f, "INCOME_VERIFICATION_RISK_SIGNALS"),
        }
    }
}

impl Default for SandboxIncomeWebhookFireRequestWebhookCode {
    fn default() -> SandboxIncomeWebhookFireRequestWebhookCode {
        Self::Verification
    }
}

