/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.586.4
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SandboxIncomeFireWebhookResponse : SandboxIncomeFireWebhookResponse defines the response schema for `/sandbox/income/fire_webhook`
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SandboxIncomeFireWebhookResponse {
    /// A unique identifier for the request, which can be used for troubleshooting. This identifier, like all Plaid identifiers, is case sensitive.
    #[serde(rename = "request_id")]
    pub request_id: String,
}

impl SandboxIncomeFireWebhookResponse {
    /// SandboxIncomeFireWebhookResponse defines the response schema for `/sandbox/income/fire_webhook`
    pub fn new(request_id: String) -> SandboxIncomeFireWebhookResponse {
        SandboxIncomeFireWebhookResponse {
            request_id,
        }
    }
}

