/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.482.3
 * 
 * Generated by: https://openapi-generator.tech
 */

/// SingleDocumentRiskSignal : Object containing all risk signals and relevant metadata for a single document



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct SingleDocumentRiskSignal {
    #[serde(rename = "document_reference")]
    pub document_reference: crate::models::RiskSignalDocumentReference,
    /// Array of attributes that indicate whether or not there is fraud risk with a document
    #[serde(rename = "risk_signals")]
    pub risk_signals: Vec<crate::models::DocumentRiskSignal>,
    #[serde(rename = "risk_summary")]
    pub risk_summary: crate::models::DocumentRiskSummary,
}

impl SingleDocumentRiskSignal {
    /// Object containing all risk signals and relevant metadata for a single document
    pub fn new(document_reference: crate::models::RiskSignalDocumentReference, risk_signals: Vec<crate::models::DocumentRiskSignal>, risk_summary: crate::models::DocumentRiskSummary) -> SingleDocumentRiskSignal {
        SingleDocumentRiskSignal {
            document_reference,
            risk_signals,
            risk_summary,
        }
    }
}


