/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.586.4
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// TotalMonthlyIncomeInsights : Details about about the total monthly income
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TotalMonthlyIncomeInsights {
    /// The aggregated income for the 30 days prior to subscription date
    #[serde(rename = "baseline_amount")]
    pub baseline_amount: f64,
    /// The aggregated income of the last 30 days
    #[serde(rename = "current_amount")]
    pub current_amount: f64,
}

impl TotalMonthlyIncomeInsights {
    /// Details about about the total monthly income
    pub fn new(baseline_amount: f64, current_amount: f64) -> TotalMonthlyIncomeInsights {
        TotalMonthlyIncomeInsights {
            baseline_amount,
            current_amount,
        }
    }
}

