/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.586.4
 * 
 * Generated by: https://openapi-generator.tech
 */

/// TransferPlatformPersonCreateResponse : Defines the response schema for `/transfer/platform/person/create`



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct TransferPlatformPersonCreateResponse {
    /// A unique identifier for the request, which can be used for troubleshooting. This identifier, like all Plaid identifiers, is case sensitive.
    #[serde(rename = "request_id")]
    pub request_id: String,
    /// An ID that should be used when submitting additional requirements that are associated with this person.
    #[serde(rename = "person_id")]
    pub person_id: String,
}

impl TransferPlatformPersonCreateResponse {
    /// Defines the response schema for `/transfer/platform/person/create`
    pub fn new(request_id: String, person_id: String) -> TransferPlatformPersonCreateResponse {
        TransferPlatformPersonCreateResponse {
            request_id,
            person_id,
        }
    }
}


