/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.586.4
 * 
 * Generated by: https://openapi-generator.tech
 */

/// TransferIntentGet : Represents a transfer intent within Transfer UI.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct TransferIntentGet {
    /// Plaid's unique identifier for a transfer intent object.
    #[serde(rename = "id")]
    pub id: String,
    /// The datetime the transfer was created. This will be of the form `2006-01-02T15:04:05Z`.
    #[serde(rename = "created")]
    pub created: String,
    #[serde(rename = "status")]
    pub status: crate::models::TransferIntentStatus,
    /// Plaid's unique identifier for the transfer created through the UI. Returned only if the transfer was successfully created. Null value otherwise.
    #[serde(rename = "transfer_id", deserialize_with = "Option::deserialize")]
    pub transfer_id: Option<String>,
    #[serde(rename = "failure_reason", deserialize_with = "Option::deserialize")]
    pub failure_reason: Option<crate::models::TransferIntentGetFailureReason>,
    #[serde(rename = "authorization_decision", deserialize_with = "Option::deserialize")]
    pub authorization_decision: Option<crate::models::TransferIntentAuthorizationDecision>,
    #[serde(rename = "authorization_decision_rationale", deserialize_with = "Option::deserialize")]
    pub authorization_decision_rationale: Option<crate::models::TransferAuthorizationDecisionRationale>,
    /// The Plaid `account_id` for the account that will be debited or credited. Returned only if `account_id` was set on intent creation.
    #[serde(rename = "account_id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub account_id: Option<Option<String>>,
    /// Plaid’s unique identifier for the origination account used for the transfer.
    #[serde(rename = "origination_account_id")]
    pub origination_account_id: String,
    /// The id of the funding account to use, available in the Plaid Dashboard. This determines which of your business checking accounts will be credited or debited.
    #[serde(rename = "funding_account_id")]
    pub funding_account_id: String,
    /// The amount of the transfer (decimal string with two digits of precision e.g. \"10.00\"). When calling `/transfer/authorization/create`, specify the maximum amount to authorize. When calling `/transfer/create`, specify the exact amount of the transfer, up to a maximum of the amount authorized. If this field is left blank when calling `/transfer/create`, the maximum amount authorized in the `authorization_id` will be sent.
    #[serde(rename = "amount")]
    pub amount: String,
    #[serde(rename = "mode")]
    pub mode: crate::models::TransferIntentCreateMode,
    #[serde(rename = "network", skip_serializing_if = "Option::is_none")]
    pub network: Option<crate::models::TransferIntentCreateNetwork>,
    #[serde(rename = "ach_class", skip_serializing_if = "Option::is_none")]
    pub ach_class: Option<crate::models::AchClass>,
    #[serde(rename = "user")]
    pub user: crate::models::TransferUserInResponse,
    /// A description for the underlying transfer. Maximum of 8 characters.
    #[serde(rename = "description")]
    pub description: String,
    /// The Metadata object is a mapping of client-provided string fields to any string value. The following limitations apply: The JSON values must be Strings (no nested JSON objects allowed) Only ASCII characters may be used Maximum of 50 key/value pairs Maximum key length of 40 characters Maximum value length of 500 characters 
    #[serde(rename = "metadata", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub metadata: Option<Option<::std::collections::HashMap<String, String>>>,
    /// The currency of the transfer amount, e.g. \"USD\"
    #[serde(rename = "iso_currency_code")]
    pub iso_currency_code: String,
    /// When `true`, the transfer requires a `GUARANTEED` decision by Plaid to proceed (Guarantee customers only).
    #[serde(rename = "require_guarantee", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub require_guarantee: Option<Option<bool>>,
    #[serde(rename = "guarantee_decision", deserialize_with = "Option::deserialize")]
    pub guarantee_decision: Option<crate::models::TransferAuthorizationGuaranteeDecision>,
    #[serde(rename = "guarantee_decision_rationale", deserialize_with = "Option::deserialize")]
    pub guarantee_decision_rationale: Option<crate::models::TransferAuthorizationGuaranteeDecisionRationale>,
}

impl TransferIntentGet {
    /// Represents a transfer intent within Transfer UI.
    pub fn new(id: String, created: String, status: crate::models::TransferIntentStatus, transfer_id: Option<String>, failure_reason: Option<crate::models::TransferIntentGetFailureReason>, authorization_decision: Option<crate::models::TransferIntentAuthorizationDecision>, authorization_decision_rationale: Option<crate::models::TransferAuthorizationDecisionRationale>, origination_account_id: String, funding_account_id: String, amount: String, mode: crate::models::TransferIntentCreateMode, user: crate::models::TransferUserInResponse, description: String, iso_currency_code: String, guarantee_decision: Option<crate::models::TransferAuthorizationGuaranteeDecision>, guarantee_decision_rationale: Option<crate::models::TransferAuthorizationGuaranteeDecisionRationale>) -> TransferIntentGet {
        TransferIntentGet {
            id,
            created,
            status,
            transfer_id,
            failure_reason,
            authorization_decision,
            authorization_decision_rationale,
            account_id: None,
            origination_account_id,
            funding_account_id,
            amount,
            mode,
            network: None,
            ach_class: None,
            user,
            description,
            metadata: None,
            iso_currency_code,
            require_guarantee: None,
            guarantee_decision,
            guarantee_decision_rationale,
        }
    }
}


