/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.586.4
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// TransferGetRequest : Defines the request schema for `/transfer/get`
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TransferGetRequest {
    /// Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header or as part of a request body.
    #[serde(rename = "client_id", skip_serializing_if = "Option::is_none")]
    pub client_id: Option<String>,
    /// Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part of a request body.
    #[serde(rename = "secret", skip_serializing_if = "Option::is_none")]
    pub secret: Option<String>,
    /// Plaid’s unique identifier for a transfer.
    #[serde(rename = "transfer_id", skip_serializing_if = "Option::is_none")]
    pub transfer_id: Option<String>,
    /// Plaid’s unique identifier for a transfer authorization.
    #[serde(rename = "authorization_id", skip_serializing_if = "Option::is_none")]
    pub authorization_id: Option<String>,
    /// The Plaid client ID of the transfer originator. Should only be present if `client_id` is a third-party sender (TPS).
    #[serde(rename = "originator_client_id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub originator_client_id: Option<Option<String>>,
}

impl TransferGetRequest {
    /// Defines the request schema for `/transfer/get`
    pub fn new() -> TransferGetRequest {
        TransferGetRequest {
            client_id: None,
            secret: None,
            transfer_id: None,
            authorization_id: None,
            originator_client_id: None,
        }
    }
}

