/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.482.3
 * 
 * Generated by: https://openapi-generator.tech
 */

/// TransactionsRuleDetails : A representation of transactions rule details.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct TransactionsRuleDetails {
    #[serde(rename = "field")]
    pub field: crate::models::TransactionsRuleField,
    #[serde(rename = "type")]
    pub r#type: crate::models::TransactionsRuleType,
    /// For TRANSACTION_ID field, provide transaction_id. For NAME field, provide a string pattern. 
    #[serde(rename = "query")]
    pub query: String,
}

impl TransactionsRuleDetails {
    /// A representation of transactions rule details.
    pub fn new(field: crate::models::TransactionsRuleField, r#type: crate::models::TransactionsRuleType, query: String) -> TransactionsRuleDetails {
        TransactionsRuleDetails {
            field,
            r#type,
            query,
        }
    }
}


