/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.586.4
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// TransferRecurringNetwork : Networks eligible for recurring transfers.
/// Networks eligible for recurring transfers.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum TransferRecurringNetwork {
    #[serde(rename = "ach")]
    Ach,
    #[serde(rename = "same-day-ach")]
    SameDayAch,
    #[serde(rename = "rtp")]
    Rtp,

}

impl std::fmt::Display for TransferRecurringNetwork {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Ach => write!(f, "ach"),
            Self::SameDayAch => write!(f, "same-day-ach"),
            Self::Rtp => write!(f, "rtp"),
        }
    }
}

impl Default for TransferRecurringNetwork {
    fn default() -> TransferRecurringNetwork {
        Self::Ach
    }
}

