/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.586.4
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// TransferMetricsGetReturnRatesOverInterval : Details regarding return rates.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TransferMetricsGetReturnRatesOverInterval {
    /// The overall return rate.
    #[serde(rename = "overall_return_rate", skip_serializing_if = "Option::is_none")]
    pub overall_return_rate: Option<String>,
    /// The unauthorized return rate.
    #[serde(rename = "unauthorized_return_rate", skip_serializing_if = "Option::is_none")]
    pub unauthorized_return_rate: Option<String>,
    /// The administrative return rate.
    #[serde(rename = "administrative_return_rate", skip_serializing_if = "Option::is_none")]
    pub administrative_return_rate: Option<String>,
}

impl TransferMetricsGetReturnRatesOverInterval {
    /// Details regarding return rates.
    pub fn new() -> TransferMetricsGetReturnRatesOverInterval {
        TransferMetricsGetReturnRatesOverInterval {
            overall_return_rate: None,
            unauthorized_return_rate: None,
            administrative_return_rate: None,
        }
    }
}

