/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.586.4
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// UserAccountSessionGetResponse : UserAccountSessionGetResponse defines the response schema for `/user_account/session/get`
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UserAccountSessionGetResponse {
    #[serde(rename = "identity", deserialize_with = "Option::deserialize")]
    pub identity: Option<models::UserAccountIdentity>,
    #[serde(rename = "items")]
    pub items: Vec<models::UserAccountItem>,
    /// A unique identifier for the request, which can be used for troubleshooting. This identifier, like all Plaid identifiers, is case sensitive.
    #[serde(rename = "request_id")]
    pub request_id: String,
}

impl UserAccountSessionGetResponse {
    /// UserAccountSessionGetResponse defines the response schema for `/user_account/session/get`
    pub fn new(identity: Option<models::UserAccountIdentity>, items: Vec<models::UserAccountItem>, request_id: String) -> UserAccountSessionGetResponse {
        UserAccountSessionGetResponse {
            identity,
            items,
            request_id,
        }
    }
}

