/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.586.4
 * 
 * Generated by: https://openapi-generator.tech
 */

/// UserDataOverview : metadata for the set of insights provided in `TransactionsUserInsightsGetResponse`



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct UserDataOverview {
    /// The total number of transactions.
    #[serde(rename = "transaction_count")]
    pub transaction_count: i32,
    /// The date of the oldest transaction processed to generate insights.
    #[serde(rename = "oldest_transaction_date", skip_serializing_if = "Option::is_none")]
    pub oldest_transaction_date: Option<String>,
    /// The date of the newest transaction processed to generate insights.
    #[serde(rename = "newest_transaction_date", skip_serializing_if = "Option::is_none")]
    pub newest_transaction_date: Option<String>,
    /// The range of days of transactions available.
    #[serde(rename = "days_available")]
    pub days_available: i32,
    /// Sum of outflow amounts.
    #[serde(rename = "total_outflows")]
    pub total_outflows: f64,
    /// Sum of inflow amounts.
    #[serde(rename = "total_inflows")]
    pub total_inflows: f64,
}

impl UserDataOverview {
    /// metadata for the set of insights provided in `TransactionsUserInsightsGetResponse`
    pub fn new(transaction_count: i32, days_available: i32, total_outflows: f64, total_inflows: f64) -> UserDataOverview {
        UserDataOverview {
            transaction_count,
            oldest_transaction_date: None,
            newest_transaction_date: None,
            days_available,
            total_outflows,
            total_inflows,
        }
    }
}


