/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.586.4
 * 
 * Generated by: https://openapi-generator.tech
 */

/// VerifySmsDetailsStatus : The outcome status for the associated Identity Verification attempt's `verify_sms` step. This field will always have the same value as `steps.verify_sms`.

/// The outcome status for the associated Identity Verification attempt's `verify_sms` step. This field will always have the same value as `steps.verify_sms`.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum VerifySmsDetailsStatus {
    #[serde(rename = "success")]
    Success,
    #[serde(rename = "failed")]
    Failed,

}

impl ToString for VerifySmsDetailsStatus {
    fn to_string(&self) -> String {
        match self {
            Self::Success => String::from("success"),
            Self::Failed => String::from("failed"),
        }
    }
}

impl Default for VerifySmsDetailsStatus {
    fn default() -> VerifySmsDetailsStatus {
        Self::Success
    }
}




