/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.586.4
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// WalletIsoCurrencyCode : An ISO-4217 currency code, used with e-wallets and transactions.
/// An ISO-4217 currency code, used with e-wallets and transactions.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum WalletIsoCurrencyCode {
    #[serde(rename = "GBP")]
    Gbp,
    #[serde(rename = "EUR")]
    Eur,

}

impl std::fmt::Display for WalletIsoCurrencyCode {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Gbp => write!(f, "GBP"),
            Self::Eur => write!(f, "EUR"),
        }
    }
}

impl Default for WalletIsoCurrencyCode {
    fn default() -> WalletIsoCurrencyCode {
        Self::Gbp
    }
}

