[package]
name = "bonk-ast-errorless"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0.194"
bonk-ast = { path = "../bonk-ast" }

[dev-dependencies]
insta = "1.34.0"
