[package]
name = "bonk-ast"
version = "0.1.0"
edition = "2021"

[dependencies]
tree-sitter = "~0.20.10"
tree-sitter-bonk = { path = "../tree-sitter-bonk" }
chrono = "0.4.31"

[build-dependencies]
cc = "1.0"
